### ISSUE TITLE
Reader not usable on Chrome 43

### ISSUE THREAD

**Issue by rgaudin** [kiwix/libkiwix#1010]
Chrome 43 (on Android 5.1.1) is a **very old** (~2015) browser that is unfortunately being used by thousands of devices with Kiwix Hotspot.

The _new_ kiwix-serve reader doesn't work on it
![Screenshot_2023-10-24-14-09-28](https://github.com/kiwix/libkiwix/assets/57929/91cf65b5-231c-496f-ab74-85c932cc6359)

**Console**

```
Uncaught SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
```

I see that even ES6 is [not supported](https://caniuse.com/?search=ES6) in this version

Viewer doesn't work either

![viewer](https://github.com/kiwix/libkiwix/assets/57929/bc7ef45a-b85d-4d06-bf0b-f797db96fbae)

**Console**

```
Uncaught SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
viewer:75 Uncaught ReferenceError: on_content_load is not defined
viewer:33 Uncaught ReferenceError: setupViewer is not defined
https://library.kiwix.org/content/favicon.ico Failed to load resource: the server responded with a status of 404 (OK)
```

ZIM content (`/content` endpoint) works

![content](https://github.com/kiwix/libkiwix/assets/57929/04b43d06-eecb-4995-9d4f-4735cbd0c5cf)

**Comment by kelson42** [comment]
@rgaudin How big of a problem is that for Kiwix Hotspot?

**Comment by rgaudin** [comment]
We don't use home page but we use the reader for the toolbar : link to home, search and suggestions.

**Comment by kelson42** [comment]
@rgaudin OK, serious problem here. Do we have a way to reproduce this behaviour on a recent OS? Do we have a way to way to have a portable version of such a very old browser?

**Comment by mgautierfr** [comment]
What about the nojs endpoint (https://library.kiwix.org/nojs) ?

**Comment by rgaudin** [comment]
I don't know what's possible but here's what I did:

- Download a Win7 ISO and create a VM
- [Download Chrome 43](http://software.oldversion.com/download.php?f=YTo1OntzOjQ6InRpbWUiO2k6MTY5ODE0ODQ3NDtzOjI6ImlkIjtpOjIzMDEzO3M6NDoiZmlsZSI7czozNjoiZ29vZ2xlLWNocm9tZS00My0wLTIzNTctNjUtMzJiaXQubXNpIjtzOjM6InVybCI7czo2NjoiaHR0cDovL3d3dy5vbGR2ZXJzaW9uLmNvbS93aW5kb3dzL2dvb2dsZS1jaHJvbWUtNDMtMC0yMzU3LTY1LTMyYml0IjtzOjQ6InBhc3MiO3M6MzI6IjcxYWY3MDRmYzNlYmExYzA5OTY0MmIzMGE1MTFlYzE4Ijt9) from [old versions](http://www.oldversion.com/windows/google-chrome/)
- Make sure it doesn't auto update:
  - `msconfig` -> Services -> Untick both Google update services
  - restart
  - Rename `C:\Program Files (x86)\Google\Update` folder (I used `NoUpdate`)
- At this point, I have a working Chrome 43 but Let's Encrypt Root CA is not present.
- https://valid-isrgrootx1.letsencrypt.org/ should display an error message
- Download root CA https://letsencrypt.org/certs/isrgrootx1.der
- Open and choose to Install (manually select `Trusted Root CA`)
- Now when you look at the cert property it should be OK
- Restart Chrome and test https://valid-isrgrootx1.letsencrypt.org/ again. If it's OK, you're good to test library.kiwix.org

**Comment by rgaudin** [comment]
> What about the nojs endpoint (https://library.kiwix.org/nojs) ?

Of course this works but it uses `/content` so there's no toolbar

**Comment by kelson42** [comment]
@rgaudin will have a look to assess how the solutions could look like. In particular we should assess if the code can not be fixed within a few hours to work on these older browsers.

**Comment by kelson42** [comment]
@rgaudin @mgautierfr Considering this ticket is blocking release of `13.0.0` and that this release is necessary to move forward on our Apple custom app effort. I would propose to move it to a `13.0.1` milestone. Would not change the priority, but remove a dependence.

**Comment by rgaudin** [comment]
I've looked into it a bit and the result is that it's not easy. That Chrome version is really old and lacks tons of features (that we are currently using) such as `let` and `const` variable declaration, `async` functions, arrow functions, functions default params.

As discussed yesterday, we've decided to close this as not-planned.
