### ISSUE TITLE
UI language selector seems to not display properly anymore

### ISSUE THREAD

**Issue by kelson42** [kiwix/libkiwix#1021]
See:
![image](https://github.com/kiwix/libkiwix/assets/1029718/464ad11f-b298-487b-bddb-a5feabffec0f)

The UI language button should:
* Stick on the right like on the welcome page
* Be the same size like other button

Solution:
* Stick the button on the right (should be easy)
* Make the other buttons a bit bigger (like the taskbar) so they all have the same size (like the UI language switcher)

**Comment by veloman-yunkan** [comment]
This is not a regression, since on the viewer page the UI language selector has always been next to the search bar.

> Solution:
> 
>     * Stick the button on the right (should be easy)

That's how I wanted it to be when it was introduced, but my initial attempts failed. I will try harder now.

> 
>     * Make the other buttons a bit bigger (like the taskbar) so they all have the same size (like the UI language switcher)

This one should be really easy.
