### ISSUE TITLE
failed in installing in manjaro

### ISSUE THREAD

**Issue by dzwdev** [kiwix/libkiwix#1031]
i successfully compiled kiwixlib and i run the installation code:
` sudo ninja -C build install            1 ✘  30s  
ninja: Entering directory `build'
[0/1] Installing files.
Installing src/libkiwix.so.13.0.0 to /usr/local/lib
Installing /home/pc/Downloads/libkiwix-main/include/book.h to /usr/local/include/kiwix
Installing /home/pc/Downloads/libkiwix-main/include/bookmark.h to /usr/local/include/kiwix
Installing /home/pc/Downloads/libkiwix-main/include/common.h to /usr/local/include/kiwix
Installing /home/pc/Downloads/libkiwix-main/include/library.h to /usr/local/include/kiwix
Installing /home/pc/Downloads/libkiwix-main/include/manager.h to /usr/local/include/kiwix
Installing /home/pc/Downloads/libkiwix-main/include/downloader.h to /usr/local/include/kiwix
Installing /home/pc/Downloads/libkiwix-main/include/search_renderer.h to /usr/local/include/kiwix
Installing /home/pc/Downloads/libkiwix-main/include/server.h to /usr/local/include/kiwix
Installing /home/pc/Downloads/libkiwix-main/include/kiwixserve.h to /usr/local/include/kiwix
Installing /home/pc/Downloads/libkiwix-main/include/name_mapper.h to /usr/local/include/kiwix
Installing /home/pc/Downloads/libkiwix-main/include/tools.h to /usr/local/include/kiwix
Installing /home/pc/Downloads/libkiwix-main/include/version.h to /usr/local/include/kiwix
Installing /home/pc/Downloads/libkiwix-main/build/src/kiwix_config.h to /usr/local/include/kiwix
Installing /home/pc/Downloads/libkiwix-main/scripts/kiwix-compile-resources.1 to /usr/local/share/man/man1
Installing /home/pc/Downloads/libkiwix-main/scripts/kiwix-compile-i18n.1 to /usr/local/share/man/man1
Installing /home/pc/Downloads/libkiwix-main/scripts/kiwix-compile-resources to /usr/local/bin
Installing /home/pc/Downloads/libkiwix-main/scripts/kiwix-compile-i18n to /usr/local/bin
Installing /home/pc/Downloads/libkiwix-main/build/kiwix.pc to /usr/local/lib/pkgconfig
Installing symlink pointing to libkiwix.so.13.0.0 to /usr/local/lib/libkiwix.so.13
Installing symlink pointing to libkiwix.so.13 to /usr/local/lib/libkiwix.so
`

in this path: /usr/local/lib/pkgconfig/   i find: kiwix.pc
but when trying to compile the kiwix desktop i get this error:
qmake .                                              ✔ 
Package kiwix was not found in the pkg-config search path.
Perhaps you should add the directory containing `kiwix.pc'
to the PKG_CONFIG_PATH environment variable
Package 'kiwix', required by 'virtual:world', not found
Package kiwix was not found in the pkg-config search path.
Perhaps you should add the directory containing `kiwix.pc'
to the PKG_CONFIG_PATH environment variable
Package 'kiwix', required by 'virtual:world', not found

how to solve this?
the kiwixlib in the AUR repo is not the latest version

**Comment by kelson42** [comment]
@dzwdev Thank you for your information, just FYI, the official name has changed from "kiwixlib" to "libkiwix" a few years ago. Maybe - if this is needed - update the package name.

**Comment by kelson42** [comment]
@dzwdev kiwix-desktop 2.2 does compile against libkiwix 12, not libkiwix 13. Pretty sure this is the problem you face.

**Comment by dzwdev** [comment]
thank you for your help. i used PKGBUILD in manjaro and now i could install it successfully.
