### ISSUE TITLE
kiwix::Downloader may miss a quickly finished download

### ISSUE THREAD

**Issue by veloman-yunkan** [kiwix/libkiwix#1049]
`kiwix::Downloader` only intercepts (and caches) downloads while they are in waiting or active state. As a result a small download that is completed before an access to it via `kiwix::Downloader` is attempted will never be returned.

**Comment by kelson42** [comment]
@veloman-yunkan This sounds a very serious problem, even if user reports mostly problems with big downloads. Eventually, this bug should probably be fix ASAP... Or do I miss so ething?

**Comment by veloman-yunkan** [comment]
I will fix it together with the other download-related bugs in kiwix-desktop (on which I am working currently).

**Comment by mgautierfr** [comment]
While you are working on this, you may want to investigate the JSON-RPC over WebSocket of aria2
(https://aria2.github.io/manual/en/html/aria2c.html#rpc-interface)

We would need a client library that support WebSocket, but it would allow aria to send notification back to us, and so we would have to pull information, just wait for notification.

**Comment by veloman-yunkan** [comment]
Well, this ticket turned out to be a false alarm caused by a problem I was seeing in `kiwix-desktop`. I was quick to blame it on `kiwix::Downloader` after looking only at `Downloader::getDownload()` and noticing that when called with a download-id missing from its cache it only checks active and waiting downloads:

https://github.com/kiwix/libkiwix/blob/1ba588272c91e8ec59847311e1cb083be6a3a316/src/downloader.cpp#L184-L204

Now I see that download-ids are added to the cache as soon as they are obtained from aria in `Downloader::startDownload()`:

https://github.com/kiwix/libkiwix/blob/1ba588272c91e8ec59847311e1cb083be6a3a316/src/downloader.cpp#L169-L182

Since the download cache is [never pruned](https://github.com/kiwix/libkiwix/issues/1050) the bug observed in `kiwix-desktop` should have a different explanation, the most likely one (though also a purely hypothetical one, as now I can't reproduce the bug) being that completion of the download was properly detected but improperly handled - the download id registered with the book was reset but the download kept being queried with that empty invalid id.
