### ISSUE TITLE
Should external catcher relax on scheme change?

### ISSUE THREAD

**Issue by rgaudin** [kiwix/libkiwix#1058]
I noticed that in an HTTP zimit1 scenario, when accessing the ZIM, warc2zim offers to switch to HTTPs in order to allow Service Workers.

<img width="1146" alt="Screenshot 2024-02-21 at 15 06 02" src="https://github.com/kiwix/libkiwix/assets/57929/a54d2bff-447b-46ce-864c-17b38698fba6">

When clicking this link, I get the external catcher

<img width="1146" alt="Screenshot 2024-02-21 at 15 06 28" src="https://github.com/kiwix/libkiwix/assets/57929/6289c00f-e701-48cb-beba-4b80e25f64ca">

As a user, I was surprised by this because it didn't feel like I was going online (and I wasn't).

I wonder if we should relax our `isExternalUrl()` check to allow identical URLs but on a different scheme 🤔

https://github.com/kiwix/libkiwix/blob/86100b39ed4b0cc5bd699ae237d2ebad5a6deb68/static/skin/viewer.js#L313-L320

**Comment by mgautierfr** [comment]
Seems indeed something to do. Especially we are redirecting our user to a https url.

---

But for the record, cross-origin differentiate between http and https.
I don't think it is important here, but somehow related and good to remember.

**Comment by kelson42** [comment]
Not sure here how would look like the next step?

**Comment by kelson42** [comment]
@rgaudin I propose to close this issue as WONTFIX as this scenario is very much related to kind of ZIM files which we don't release anymore. Implementing something woukd complexify the code for "no" concrete use case.
