### ISSUE TITLE
sync releases with library users

### ISSUE THREAD

**Issue by stefantalpalaru** [kiwix/libkiwix#1063]
Please release kiwix-desktop and kiwix-tools at the same time you release a backwards-incompatible libkiwix. It would help us packagers not waste our time trying to figure out the compatibility.

**Comment by kelson42** [comment]
We are following [semantic versioning](https://semver.org/), as such the backward compatibility of any new release should be clear. `13.1.0` is.... or at least: should be. Do you face any kind of problem?

**Comment by stefantalpalaru** [comment]
> Do you face any kind of problem?

Yes. Neither libkiwix-13.0.0 nor 13.1.0 work with kiwix-desktop-2.3.1 or kiwix-tools-3.6.0 - which are the latest releases.

> We are following [semantic versioning](https://semver.org/)

That's marvellous. How about releasing software that actually works with this library? It would also help you get bug reports, if this newfangled library version is actually used by actual users.

> the backward compatibility of any new release should be clear

It's not. I get a GitHub notification that a new libkiwix has been released. I bump the package version in my [Gentoo overlay](https://github.com/stefantalpalaru/gentoo-overlay/tree/master/www-misc), then try to rebuild the packages that depend on it. That fails, so I revert back and wonder why you made me waste my time.

This has happened twice now. Do you want your software to reach end-users, or don't you?

**Comment by kelson42** [comment]
> > Do you face any kind of problem?
> 
> Yes. Neither libkiwix-13.0.0 nor 13.1.0 work with kiwix-desktop-2.3.1 or kiwix-tools-3.6.0 - which are the latest releases.

This is normal, kiwix-desktop-2.3.1 is based on libkiwix12. I have just pushed a PR to be even more explicit (than the semantic versioning) https://github.com/kiwix/kiwix-desktop/pull/1044
 
> > We are following [semantic versioning](https://semver.org/)
> 
> That's marvellous. How about releasing software that actually works with this library? It would also help you get bug reports, if this newfangled library version is actually used by actual users.

We release when we are ready. This is, in any case, an other kind of discussion.

> > the backward compatibility of any new release should be clear
> 
> It's not. I get a GitHub notification that a new libkiwix has been released. I bump the package version in my [Gentoo overlay](https://github.com/stefantalpalaru/gentoo-overlay/tree/master/www-misc), then try to rebuild the packages that depend on it. That fails, so I revert back and wonder why you made me waste my time.

Kiwix-desktop 2.3.1 should not depend on anything else than libkiwix 12. Let me know if you see anything we could do to make this more clear. https://github.com/kiwix/kiwix-desktop/pull/1044 might help, but I have the feeling that the wrong assumption is more in your Gentoo package file.

**Comment by stefantalpalaru** [comment]
> We release when we are ready.

How can you be ready to release libkiwix, when you are not ready to release any other software that uses it?

---

Here's a real-life example of synced releases. The same people developing [PyTorch](https://github.com/pytorch/pytorch) also develop [TorchVision](https://github.com/pytorch/vision).

Do you know how much time passed between the release of PyTorch-2.2.1 and that of TorchVision-0.17.1 (which supports the former)? Forty-nine minutes.
