### ISSUE TITLE
Add get_zim_id to Result

### ISSUE THREAD

**Issue by automactic** [kiwix/libkiwix#107]
Currently, the `Result` class has  `get_readerIndex` but no `get_zim_id `. 

Users have to keep an additional vector of zim file IDs somewhere to track which zim file a result is in. Users also cannot use the property `readers` of `Searcher` for this purpose, since it is protected (and it probably should be). 

But since `Searcher` already have the `readers`, it can save users some trouble by providing this info in `Result`. To go a bit further, we might just deprecate `get_readerIndex`, since providing the ID is probably more useful than index.

**Comment by kelson42** [comment]
@mgautierfr Hmmm... might that be that `get_readerIndex` should probably be `protected` too?

**Comment by automactic** [comment]
No, it should not. Imagine if one added a.zim, b.zim to searcher, `get_readerIndex` allows you to tell if a result is from a.zim or b.zim, depending on the order they are added. What I am suggesting here is to replace `get_readerIndex` with something like `get_readerID`, so the user of Searcher does not have to keep track of the order zim files are added.

**Comment by mhutti1** [comment]
For me personally I would like to see kiwixreader to be able to read zim files of the format zimid(or zim name).publisherdomain/localurl At the moment we need to keep track of all kiwix readers and the current readers. One annoying example of this is the current search process. We get results. We don't know which ZIM file the URLs correlate to so we don't know which one to open the URL with. There are two ways to resolve this. First is to use getcontent to render the result directly. This however would mean that links in the searched page that are locally formatted wouldn't work as they would be looking up in the wrong zim. So as @automactic mentions we need to keep a mapping of indexes to kiwixreaders and swap out the default reader whenever the content changes reader in a very weird manor. Giving direct access to the reader would help but imo not needing to switch the reader at all would be the best solution and would increase the interchangeability of ZIM files immensely.

**Comment by kelson42** [comment]
@MananJethwani @mgautierfr This is a quite old ticket and wanted to ask if the new libzim/libkiwix API takes these remark in account?

**Comment by mgautierfr** [comment]
We can only know the index of the database used in multisearch from xapian.
We we create a Search on libzim side, we keep a reference to the archives to be able to get the article content from the right archive using this index.

We should easily be able (in libzim) to return the zim id from it to avoid the user to keep  keep track of the order zim files are added.
We will probably not add it in kiwix-lib, mainly because of https://github.com/kiwix/kiwix-lib/issues/430

**Comment by maneeshpm** [comment]
@mgautierfr Are you planning to add this in your new search API pr? If not, I have it already implemented for testing purposes and can open a pr.

**Comment by kelson42** [comment]
@maneeshpm Now that you have built this part, feel free to make the libkiwix PR. Don’t wait too much.

**Comment by maneeshpm** [comment]
@kelson42 Sounds good. I'll get started on that.
