### ISSUE TITLE
Suggestions for improving Kiwix-server for blind people

### ISSUE THREAD

**Issue by patrick-emmabuntus** [kiwix/libkiwix#1072]
Hello the Kiwix team,

To allow Kiwix-server to add accessibility functions for the blind people, I suggest you add shortcuts in the template files for pages read by the Kiwix server in the Kiwix common functions library.

For this I suggest you use the word "accesskey" to define these shortcuts, see https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/accesskey

Of course, there is a risk of conflict of these shortcuts with Browsers or the screen reader. 
In my case with Orca and Firefox, I used the following keys:
- S: to access the search area so Alt+Shift+S
- D: to access an article at random so Alt+Shift+D
- N: to access the home page of the encyclopedia so Alt+Shift+N
- W: to access the encyclopedias home page so Alt+Shift+W

Here are the patch files used to do this [libkiwix.tar.gz](https://github.com/kiwix/libkiwix/files/14911343/libkiwix.tar.gz)

**Comment by kelson42** [comment]
@patrick-emmabuntus Thank you for your issue, here a few remarks:
* I have no know-how to know what could be a proper accesskey for these formulars
* Ready to merge as it after proper review from developer
* Can you please open a PR to ease the process?

**Comment by patrick-emmabuntus** [comment]
Hi @kelson42 
>     * I have no know-how to know what could be a proper accesskey for these formulars
accesskey is simply a command in an html file to define the function key that will be associated with this button. Nothing more so just put in the html tag of the button accesskey="x". When the user presses alt+shift and X in this example this will launch the command associated with this button
>     * Ready to merge as it after proper review from developer
>     * Can you please open a PR to ease the process?

I'll try but I've never done this.

**Comment by patrick-emmabuntus** [comment]
Hello @kelson42 

I created a fork of the main branch, but when I compile this I have a package called libkiwix10_0.0.0_amd64.deb.

This is not normal, personally on Debian 12 the package is called libkiwix11_11.0.0-2+b2_amd64.deb: https://packages.debian.org/bookworm/libkiwix11

Next time, I compile the sources before making changes in the code, because there were files that we changed names and it's not easy to find them.

Which branch should I use to make the pull request?

**Comment by kelson42** [comment]
> I created a fork of the main branch, but when I compile this I have a package called libkiwix10_0.0.0_amd64.deb.
> This is not normal, personally on Debian 12 the package is called libkiwix11_11.0.0-2+b2_amd64.deb: https://packages.debian.org/bookworm/libkiwix11

@patrick-emmabuntus Sorry for late feedback. I don't know what your are doing as I don't have the command your run. What is sure is that creating a deb file is not part of the standard compilation. Please read the `README.md` to get the compilation instruction. This is unrelated to this issue, please open a new issue if somehow you need support of an other point.
 
> Which branch should I use to make the pull request?

You can use/call your branch like you want, I just want only the changes related to this issue. If you have other ideas of improvements, let us treat this in a different issue/PR.

**Comment by kelson42** [comment]
@patrick-emmabuntus Finally I made the PR myself to finaly be able to move forward. That said, this is really better if possible if people make their PR themselves. Thank you anyway for your patience.
