### ISSUE TITLE
„Blk“ language is not displayed properly in Kiwix Serve language filter

### ISSUE THREAD

**Issue by kelson42** [kiwix/libkiwix#1076]
<img width="1024" alt="image" src="https://github.com/kiwix/libkiwix/assets/1029718/76bb0fa1-b7c2-4408-9421-fa9672f1c37f">

See https://en.wikipedia.org/wiki/Pa%27O_language

**Comment by kelson42** [comment]
Same for „lld“, https://en.wikipedia.org/wiki/Ladin_language

**Comment by kelson42** [comment]
And 
<img width="1024" alt="image" src="https://github.com/kiwix/libkiwix/assets/1029718/1194a79f-77ec-4f4e-a1ac-353915d61f92">

**Comment by kelson42** [comment]
And 
<img width="1024" alt="image" src="https://github.com/kiwix/libkiwix/assets/1029718/62c3a0c4-a4a5-4a5a-a9f2-a3506fe77306">

**Comment by kelson42** [comment]
And 
<img width="1024" alt="image" src="https://github.com/kiwix/libkiwix/assets/1029718/130f543d-d206-4024-a310-ce110aebacd9">

**Comment by kelson42** [comment]
And codes twi, tgl, tay, szi

**Comment by juuz0** [comment]
Good ol' ICU not knowing these languages :>

**Comment by kelson42** [comment]
Yes, currently fixing them
