### ISSUE TITLE
library.kiwix.org appears to have stopped updating

### ISSUE THREAD

**Issue by salfter** [kiwix/libkiwix#1078]
I'm not sure if this is the right place for this, but gutenberg_en_all is showing as having last been updated in August 2023 (though I've previously downloaded an archive produced in January 2024).  Also, wikipedia_en_all_maxi is showing as having last been updated in January 2024.  Has something happened with library.kiwix.org such that it is showing old content or isn't updating?

**Comment by rgaudin** [comment]
Nope, those are the latest two versions available ; as can be seen on https://download.kiwix.org/zim/
