### ISSUE TITLE
Prevent the same zim file from being added twice

### ISSUE THREAD

**Issue by automactic** [kiwix/libkiwix#108]
Currently the implementation of `void Searcher::add_reader` simply store `Reader` in a vector. User can perform the following actions:

- add the same `Reader` object multiple times
- add different  `Reader` instance of the same zim file 

which may result in multiple xapian database of the same zim file being added to the search. (I am not sure if `zim::Search` handles such cases).

It might be better to figure out if the `Reader` of a specific zim file is already added to the search. If already added, simply return and do nothing. We might be able to achieve this by using a `std::unordered_map<std::string, std::shared_ptr<kiwix::Reader>> readers` internally.

**Comment by kelson42** [comment]
@mgautierfr good idea?

**Comment by maneeshpm** [comment]
@mgautierfr This is something we have to think about before dropping `kiwix::Searcher`. Naturally once we drop the wrapper, we will switch to use `zim::Searcher` in all the projects. But is there an API in libzim that lets the user add a new Archive to the searcher once a `zim::Searcher` object is created? Is `Searcher::add_reader` equivalent even necessary in `zim::Searcher`?

**Comment by mgautierfr** [comment]
We may use a map as @automactic suggests. But it must be ordered as it is the main purpose of the vector (find the correct archive from the db index returned by xapian)

**Comment by kelson42** [comment]
We are ready to implement this ticket now I guess.
