### ISSUE TITLE
Provide a thumbImage path of an article

### ISSUE THREAD

**Issue by automactic** [kiwix/libkiwix#109]
It might be a good idea to provide an optional thumbImage link in search result. 

This way, when loading the search results, the apps utilizing kiwix-lib could show thumbImage alongside title and snippet. The book favicon can be displayed when thumbImage is absent. This make it obvious if a search result comes from a zim file with or without pictures, leading to a better user experience.

**Comment by kelson42** [comment]
Yes... that said I have no clue exactly how this should achieved.

**Comment by automactic** [comment]
We can do this by adding the src of a <img> (the first, for instance) in the html during indexing to [`Xapian::Documents`](https://xapian.org/docs/apidoc/html/classXapian_1_1Document.html).

**Comment by automactic** [comment]
I agree with using the `Mediawiki` API if is already implemented. But I don't think it is a good idea to put it in `<head>`, since you have to get the content of the html and build the doc tree. Why not add this as a meta of xapian document?

**Comment by kelson42** [comment]
@automactic The problem is that the for now, and as long as we do not use node-libzim, in mwoffliner, the static HTML is more or less the only way to exchange information beetween the online web site and the final ZIM file (through zimwriterfs).

**Comment by automactic** [comment]
If we utilize features in Mediawiki, why does it matter if we use node or not? Surely we can just make requests to Mediawiki API and ask for a thumbImage link for an article.

**Comment by kelson42** [comment]
This is more a request for the libzim than for libkiwix IMO. It is related to the global metadata problematic.
