### ISSUE TITLE
ZIM size advertized in library is in MB while users see a MiB value in many other places

### ISSUE THREAD

**Issue by benoit74** [kiwix/libkiwix#1095]
For instance with https://library.kiwix.org/#q=stacks, library displays 149MB while all other speak about 143MB. It is confusing.

Library:

![image](https://github.com/kiwix/libkiwix/assets/7102089/6d229f33-bc8a-471b-a052-931d7e77e1f8)

download.kiwix.org:
![image](https://github.com/kiwix/libkiwix/assets/7102089/3105180c-ff51-477a-83fa-06062e768fce)

Firefox download box:
![image](https://github.com/kiwix/libkiwix/assets/7102089/c45b81f3-90db-48da-825d-faaf8e61a71f)

Chrome download box:
![image](https://github.com/kiwix/libkiwix/assets/7102089/0189d3c4-86fc-4ca3-91e9-8a6d2286f7b0)

Mirrorbrain meta information:
https://download.kiwix.org/zim/zimit/stacks.math.columbia.edu_en_all_2024-06.zim?mirrorlist

![image](https://github.com/kiwix/libkiwix/assets/7102089/9a1ca355-fcd6-46cf-b085-3a55f6da0b88)

MacOS Finder:
![image](https://github.com/kiwix/libkiwix/assets/7102089/024153ad-d025-4662-8ca0-1026328400f5)

It comes from the classical confusion between MiB and MB (see e.g. https://tecadmin.net/difference-between-megabyte-megabit-and-mebibyte/). While the value displayed is technically correct (we really have a 149MB file, 143MiB), everywhere else users have a MiB value displayed instead of MB. I think we should align with what looks mostly like a consensus (Apple is different ... as always ^^) and write `143MiB` to be precise. 

I also suggest we drop the precision to only 3 digits, everything else is just noise : 149Mib, 1.42GiB, ...

**Comment by mgautierfr** [comment]
Agree.

We are speaking about this code : https://github.com/kiwix/libkiwix/blob/main/static/skin/index.js#L81-L90

Should be easy to fix.
