### ISSUE TITLE
ZIM Illustration is resized in the catalog UI and hence a bit blurry

### ISSUE THREAD

**Issue by benoit74** [kiwix/libkiwix#1102]
Current icon on ZIMs in the library catalog are always a bit blurry even if the real image if reasonably sharp.

![image](https://github.com/user-attachments/assets/e9f53c59-99b4-41e5-b59e-3ae7167f6751)

Real image:

![image](https://github.com/user-attachments/assets/1c7322ce-f58f-49f6-8ef5-77b8a2ad46cd)

Problem is that the image is displayed as a div background-image, and the div is not exactly 48x48 pixels, so the image is resized to few more pixels (55x60 on my device / browser). And obviously adding few pixels is just adding blur.

Image if I force background size to 48x48 pixel:

![image](https://github.com/user-attachments/assets/57a6e761-80b7-4ece-a6a2-90320b6c5212)

![image](https://github.com/user-attachments/assets/b88c01c4-d220-4ca9-939a-032b61a41171)

PS: note that just adding the "background-size: 48px 48px" is just a trick to showcase the issue, it is not deemed to be the best approach, it has not been tested on all screen sizes / browsers and it has a side effect that the image is not centered vertically and horizontal anymore. If we go this way we need at least the "background-position: center;" additional style.

**Comment by benoit74** [comment]
Side-by-side exemple (left is fixed at 48x48, right is as-of-today)

![image](https://github.com/user-attachments/assets/1094aa62-9124-4f61-81ce-957c37db0275)

**Comment by kelson42** [comment]
This is a bug, illustration (div size) should 48x48
