### ISSUE TITLE
Expose support for i18n/translation in the public C++ API

### ISSUE THREAD

**Issue by veloman-yunkan** [kiwix/libkiwix#1103]
`libkiwix` server component has been internationalized a while ago, but the support for that functionality has not been exposed in the public C++ API.

kiwix/kiwix-desktop#972 has now put enough pressure on `libkiwix` to finally start providing translation services to its C++ clients.

**Comment by kelson42** [comment]
@ShaopengLin We really need to move forward on this!

**Comment by ShaopengLin** [comment]
I am waiting for veloman to respond to my comment here [about filtering](https://github.com/kiwix/kiwix-desktop/issues/972#issuecomment-2254360573). It also affects what I need to do here.

I can put up a priliminary version for now then.
