### ISSUE TITLE
[REGRESSION] Kiwix-Build CI/CD crashes on libkiwix on aarch64

### ISSUE THREAD

**Issue by kelson42** [kiwix/libkiwix#1143]
See https://github.com/kiwix/kiwix-build/actions/runs/11154308452/job/31003365353#step:8:552

We should:
* Fix the problem
* Explain why the libkiwix CI does not have caught this compilation problem

**Comment by veloman-yunkan** [comment]
> * Explain why the libkiwix CI does not have caught this compilation problem

libkiwix CI job matrix doesn't contain the "Linux (aarch64_static, focal)" config. Likely an older version of g++ is used there.

**Comment by kelson42** [comment]
> > * Explain why the libkiwix CI does not have caught this compilation problem
> 
> libkiwix CI job matrix doesn't contain the "Linux (aarch64_static, focal)" config. Likely an older version of g++ is used there.

Both CD/CI should work with Ubuntu 20.04 (Focal). Which part does not following things properly?

**Comment by veloman-yunkan** [comment]
> > > * Explain why the libkiwix CI does not have caught this compilation problem
> > 
> > 
> > libkiwix CI job matrix doesn't contain the "Linux (aarch64_static, focal)" config. Likely an older version of g++ is used there.
> 
> Both CD/CI should work with Ubuntu 20.04 (Focal), not sure about the version of G++. Which part does not following things properly?

@kelson42 

This is the list of configs for CI jobs on Linux for the `libkiwix` repo:

- linux-x86_64-static
- linux-x86_64-dyn
- android-arm
- android-arm64

The same list for the `kiwix-build` repo is significantly longer:
- native_static
- native_dyn
- native_mixed
- wasm
- armv6_static
- armv6_dyn
- armv6_mixed
- armv8_static
- armv8_dyn
- armv8_mixed
- aarch64_static
- aarch64_dyn
- aarch64_mixed
- aarch64_musl_static
- aarch64_musl_dyn
- aarch64_musl_mixed
- x86-64_musl_static
- x86-64_musl_mixed
- i586_static
- i586_dyn
- android_arm
- android_arm64
- android_x86
- android_x86_64
 
The failed CI jobs are for aarch64 which - from what I conclude from the logs - runs under Linux via qemu and uses a different compiler.

**Comment by veloman-yunkan** [comment]
Native compiler in the CI build image is g++ version **9.4.0**.
The cross compiler for aarch64 (included in [base_deps_focal_aarch64_static_07.tar.gz](https://tmp.kiwix.org/ci/base_deps_focal_aarch64_static_07.tar.gz)) is version **6.3.0**.

```
$ mkdir base_deps_focal_aarch64_static_07
$ cd base_deps_focal_aarch64_static_07/
$ wget https://tmp.kiwix.org/ci/base_deps_focal_aarch64_static_07.tar.gz
$ tar xzf base_deps_focal_aarch64_static_07.tar.gz
$ docker run --rm -it -v $(pwd):/home/runner/builddir ghcr.io/kiwix/kiwix-build_ci_focal
runner@20b41ca6ee97:/$ cd
runner@20b41ca6ee97:~$ ./builddir/BUILD_neutral/TOOLCHAINS/aarch64/bin/aarch64-linux-gnu-g++ --version
aarch64-linux-gnu-g++ (GCC) 6.3.0
Copyright (C) 2016 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

runner@20b41ca6ee97:~$ g++ --version
g++ (Ubuntu 9.4.0-1ubuntu1~20.04.2) 9.4.0
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by kelson42** [comment]
@veloman-yunkan Thx a lot for the clarification, I will open a dedicated ticket ASAP. We should be able to get ride of qemu very soon.
