### ISSUE TITLE
kiwix-serve cant instantiate HTTP daemon on windows

### ISSUE THREAD

**Issue by rgaudin** [kiwix/libkiwix#1144]
Using https://tmp.kiwix.org/ci/dev_preview/zim-tools_windows/kiwix-tools_win-x86_64-2024-09-02.zip on Windows 11 (VM) I can't seem to start kiwix-serve.

Either as regular user or administrator, I always get the following error:

```
C:\Users\reg\test-tools>kiwix-serve.exe -p 8001 ..\python-libzim\rlz\test.zim
Unable to instantiate the HTTP daemon. The port 8001 is maybe already occupied or need more permissions to be open. Please try as root or with a port number higher or equal to 1024.
```

**Comment by sgourdas** [comment]
@kelson42 I have identified the issue and will try to put out a PR by tomorrow morning.

Also, it seems that Windows kiwix-build is working with kiwix-tools. We should update the [wiki page](https://github.com/kiwix/kiwix-build/wiki/Setup-dev-environment-en-Windows).

**Comment by kelson42** [comment]
> Also, it seems that Windows kiwix-build is working with kiwix-tools. We should update the [wiki page](https://github.com/kiwix/kiwix-build/wiki/Setup-dev-environment-en-Windows).

Can you please open a dedicated issue in kiwix-build repo?

**Comment by sgourdas** [comment]
> > Also, it seems that Windows kiwix-build is working with kiwix-tools. We should update the [wiki page](https://github.com/kiwix/kiwix-build/wiki/Setup-dev-environment-en-Windows).
> 
> Can you please open a dedicated issue in kiwix-build repo?

Opened kiwix/kiwix-build#760
