### ISSUE TITLE
Server::setAddress cannot be used more than once for an object

### ISSUE THREAD

**Issue by sgourdas** [kiwix/libkiwix#1150]

**Comment by kelson42** [comment]
@sgourdas I was not aware that many IPs could be set! This is not possible using Kiwix Server at least... is that normal? Is the `kiwix-serve` command line option mgmt not aligne with what can do the libkiwix?

**Comment by sgourdas** [comment]
> [@sgourdas](https://github.com/sgourdas) I was not aware that many IPs could be set! This is not possible using Kiwix Server at least... is that normal? Is the `kiwix-serve` command line option mgmt not aligne with what can do the libkiwix?

@kelson42 no, multiple user defined ips cannot be set. This has to do with setting the ip over and over on the same server object, but the old ip not being cleared up, ending up on misalignment. This is now fixed by resetting the m_addr field, before setting the new ip.
