### ISSUE TITLE
kiwix-server: ZIM favicon is not displayed properly in viewer

### ISSUE THREAD

**Issue by benoit74** [kiwix/libkiwix#1156]
Test ZIM (WIP on mindtouch scraper, but should be OK on this aspect): 
[tests_en_libretexts-geo.zim.txt](https://github.com/user-attachments/files/17521726/tests_en_libretexts-geo.zim.txt) (rename to .zim extension, I had to add .txt for Github to be happy)

Expected behavior: favicon is properly displayed

Observed behavior: favicon is loaded from /content/favicon.ico instead of /content/tests_en_libretexts-geo/favicon.ico

kiwix-serve version : nightly from rgaudin Docker image

Command: `docker run -it --rm -v $(pwd):/data -p 8888:8888 --entrypoint /usr/local/bin/kiwix-serve ghcr.io/rgaudin/kiwix-tools:nightly --port=8888 -b "/data/output/tests_en_libretexts-geo.zim"`

**Comment by kelson42** [comment]
Duplicate of https://github.com/kiwix/kiwix-tools/issues/159 ?

**Comment by benoit74** [comment]
Indeed, didn't search in kiwix-tools ...
