### ISSUE TITLE
Unify camel case and snake case in function names

### ISSUE THREAD

**Issue by automactic** [kiwix/libkiwix#144]
We should unify camel case and snake case in function names. For example, currently in `Searcher`, there are functions `add_reader` and `getNextResult`. We should make a decision on which style to use.

**Comment by kelson42** [comment]
@mgautierfr @veloman-yunkan @maneeshpm What is the status here? Do we at least know how it should be? How much work would be needed to fix the problem?

**Comment by maneeshpm** [comment]
@kelson We recently took a step to change the libzim SearchIterator API to use camel case. IMO most of the API code if not all of it in libzim is in camel case, so we should try to do the same here.
 
I guess this is the right time to get decided on this one so that we can at least fix the libkiwix API with this scheme before the next major release.

**Comment by kelson42** [comment]
@mgautierfr I guess this last ticket is for you. At the same time, might be a good idea to just go through the whole API and see if it looks coherent.

**Comment by veloman-yunkan** [comment]
Does this ticket apply only to the public API of libkiwix? If so then only `kiwix::Searcher` is affected. But then should be try to fix it or better get rid of `kiwix::Searcher` as suggested in #430?

**Comment by kelson42** [comment]
@veloman-yunkan This is a good news! We should get ride of it... and made necessary adaptation in kiwix-tools and kiwix-desktop.

**Comment by mgautierfr** [comment]
> Does this ticket apply only to the public API of libkiwix? 

It is mandatorry for the public API yes. For the private part, we can fix it now and fix it incrementally as we change other stuff.

> If so then only kiwix::Searcher is affected. But then should be try to fix it or better get rid of kiwix::Searcher as suggested in #430?

It is probably better to mark it as deprecated (#654), we will remove it in a future release.

**Comment by kelson42** [comment]
@mgautierfr What is the advantage to keep it now, if we remove it within a month?

**Comment by mgautierfr** [comment]
We don't break all existing code using it (Android wrapper is still based on kiwix structures). And I've not said it will be removed within a month, I've said it will be removed in the future :)

**Comment by kelson42** [comment]
Android is broken anyway, we can not release the JNI binding anymore since a year.

**Comment by mgautierfr** [comment]
I see no special reason to remove it now. Marking it as deprecated is almost straight forward.
Removing it means that we also need to remove the JNI wrapper (or adapt it). And it probably also means that we need to adapt our build system (should we continue to build android nightlies ?)

We can of course remove it now. But it would be yet another thing to do and check before doing the release. I would prefere reduce as far as possible the work to do before doing the release and handle not mandatory things after.

**Comment by kelson42** [comment]
Agree if making this deprecated is trivial. Quite sure, android nightlies are not done with cutting edge libkiwix.

**Comment by mgautierfr** [comment]
So I'm closing the issue in favor of #654, we will "simply" mark `kiwix::Searcher` as deprecated.
