### ISSUE TITLE
Iterative searcher

### ISSUE THREAD

**Issue by automactic** [kiwix/libkiwix#166]
I remember @mgautierfr told me he is planning on replace `getNext` styled searcher with an iterator. Do we have plan on if and when this will be finished? Thanks!

**Comment by kelson42** [comment]
@automactic What is the problem you want to fix?

**Comment by automactic** [comment]
There is not problem. @mgautierfr talked about updating the searcher to an iterator. I am also trying to do some modifications of my searching async system. I just want to time those two things together.

**Comment by kelson42** [comment]
To me, now, we clearly need that.

**Comment by automactic** [comment]
Could you elaborate why we need it? To me, `getNext` works, so I'd say it is not required

**Comment by kelson42** [comment]
@automactic The iterator is a C++ standard pattern to do this kind of operation and I want to use it as far as possible in place of custom API. But this is not the key point we are going to change (even if this is still open to discussion):
* I want to avoid to buffer the list of results (this should come more or less directly from Xapian)
* We should be able to iterate through all the results (not only the N first like currently)
* The search object should "live" longer even if other search requests have be ran (currently it lives only until next iteration). This implies the creation of a search cache.
* Most of this should happen in the libzim and not in the libkiwix

I hope to somehow document with Matthieu the approach we want to follow this week as a GSoC student will work on that during the summer.

**Comment by maneeshpm** [comment]
@kelson42 We already have a search_iterator implementation in libzim [here](https://github.com/openzim/libzim/blob/master/src/search_iterator.cpp) that is based on the `Xapian::MSetIterator`. In kiwix-lib this iterator is wrapped inside a `_Result` class internally. The `getNextResult()` method is just incrementing the iterator and returning it wrapped in a `_Result` object. This is perhaps done for simplicity(?). You want us to be able to use this iterator directly without a wrapper in kiwix-lib right? or do you have a different implementation idea.

**Comment by kelson42** [comment]
@maneeshpm I will let @mgautierfr further answer

**Comment by mgautierfr** [comment]
> This is perhaps done for simplicity(?)

Definitvly not :) It was this way a long time ago (before we had a xapian database).
I've keep this API for compatibility reason but it complicate all the stack.

> You want us to be able to use this iterator directly without a wrapper in kiwix-lib right?

Yes. See https://github.com/kiwix/kiwix-lib/issues/430

**Comment by maneeshpm** [comment]
Thanks @mgautierfr! It makes sense now. I agree with your comment on the linked issue. The distinction between libzim and kiwix-lib needs to be clear. This issue gets fixed once we drop the wrappers(or even without dropping them) and adapt the existing kiwix-lib to implement libzim directly.

**Comment by kelson42** [comment]
@automactic @maneeshpm https://github.com/kiwix/kiwix-tools/issues/97#issuecomment-814111663 gives a good insight in how should be the new searcher architecture.

**Comment by kelson42** [comment]
Somehow similar to #146

**Comment by kelson42** [comment]
@maneeshpm Good to me.

**Comment by maneeshpm** [comment]
@kelson42 With the merge of #536 we now have exposed `zim::SearchIterator` to libkiwix and already using it in places like [search_renderer](https://github.com/kiwix/libkiwix/blob/60f0f81286dc1364369d818b2acc18d8fc7f178a/src/search_renderer.cpp#L85) and [internal_server](https://github.com/kiwix/libkiwix/blob/60f0f81286dc1364369d818b2acc18d8fc7f178a/src/server/internalServer.cpp#L347). I believe this was the expectation from this ticket. If some projects are still using the `kiwix::Searcher`/`kiwix::Reader`, we need to go ahead and drop it in favour of libzim structures after the merge of #576.

As far as this issue is concerned,  I would call this fixed. We can close this if you and @mgautierfr agree.
