### ISSUE TITLE
Allow kiwix-serve to retrieve suggestions in the range provided by users

### ISSUE THREAD

**Issue by rashiq** [kiwix/libkiwix#242]
**Reported by kelson42 on 2013-05-13 11:33 UTC**
To allow to scroll without a end in the suggestion list.

**Comment by kelson42** [comment]
@rashiq Not sure why you have closed this issue? The feature request seems good to me! Reopening.

**Comment by kelson42** [comment]
@mgautierfr @maneeshpm I think this will be solved anyway by the new API?

**Comment by maneeshpm** [comment]
@kelson42 I don't think it is planned as of now, and I think this can be implemented irrespective of libzim. In kiwix-lib we request only 10 suggestions, so we get only 10. We can request the next 10 suggestions on the scroll event to implement this. The caching feature of new libzim API will be helpful.

**Comment by kelson42** [comment]
@maneeshpm Yes, but this is what this feature requests IMO: being able to progress freely via a window on the result vector. To the opposite of today where you give your limit, you get it and then this is over.

**Comment by mgautierfr** [comment]
> I think this will be solved anyway by the new search API, right?

The work is on kiwix-lib side, the new libzim search API will not solve the issue.

It will help for performance reason but it is already possible in libzim to query the range 10-20, 20-30 (that is what we do for fulltext search)

**Comment by maneeshpm** [comment]
@kelson42 Do you think we should change the context of the ticket to what @mgautierfr and I have mentioned, that is enabling the feature to get suggestions within a range like 10-20 on libkiwix side and proceed accordingly?

**Comment by kelson42** [comment]
@maneeshpm "yes" please do what you think is appropriate.

**Comment by maneeshpm** [comment]
Done, Thanks :smile:
