### ISSUE TITLE
Move jni to kiwix/java-libkiwix (was:Are .jar files necessary to be in the repo?)

### ISSUE THREAD

**Issue by legoktm** [kiwix/libkiwix#358]
In 82afb804e1def59bc30175c630767766fa016977 @mgautierfr added two jar files, `src/wrapper/java/org/kiwix/testing/hamcrest-core-1.3.jar` and `src/wrapper/java/org/kiwix/testing/junit-4.13.jar`.

Do those need to be in the repo since they're just for testing, or can they be installed by some java package manager? (java isn't my area of expertise)

If they are kept in the repo, I would like to document their source/license/copyright information and can submit a PR for that.

**Comment by mgautierfr** [comment]
Ideally they should not be. But we don't use a java package manager and I don't want to add one in kiwix-build/CI.

---

On a more global approach, I was partisan to have the wrappers inside the same repository of the library to make them evolve together, but on the libzim side we use the different approach to have wrappers outside of the source code. If we follow this path, we should move the JNI wrapper in a new repository. This way we could use the android build system (which I don't know) to build the wrapper (java and c++ code). The jar would be in this repository (or not), the way it is best in the java/android ecosystem. The same way, the publication of the kiwixlib and the wrapper would be left to the wrapper repository.

**Comment by legoktm** [comment]
For now I'm working around this by just deleting the two .jar files from the Debian package since they aren't needed.

> If we follow this path, we should move the JNI wrapper in a new repository.

Sounds like a good idea to me (I'm not at all an android/java person though).

**Comment by kelson42** [comment]
I guess moving the JNI to kiwix/java-libkiwix will solve the problem.

**Comment by kelson42** [comment]
This is happens now, code from `kiwix-build` and `libkiwix` will be migrated to `libkiwix-java`

**Comment by mgautierfr** [comment]
This is done with https://github.com/kiwix/libkiwix/pull/781
