### ISSUE TITLE
Jquery code should not be part of the code

### ISSUE THREAD

**Issue by kelson42** [kiwix/libkiwix#369]
It is a dependence and should be downloaded.

**Comment by mgautierfr** [comment]
I even think we should stop using jquery.

**Comment by legoktm** [comment]
Where is jquery-ui used right now? And what minimum IE version do we need to support (see http://youmightnotneedjquery.com/)?

**Comment by kelson42** [comment]
> Where is jquery-ui used right now?

AFAIK for Kiwix-serve taskbar suggestion system.

> And what minimum IE version do we need to support (see http://youmightnotneedjquery.com/)?

I don't know, I don't have big expection on this, people should use a recent browser.

**Comment by kelson42** [comment]
@MananJethwani I would choose pretty much the same approach as the one used by @mgautierfr for the ZIM test files in  openzim/libzim. See https://github.com/openzim/libzim/pull/538/files.
