### ISSUE TITLE
CI should be run on pull_request event

### ISSUE THREAD

**Issue by mgautierfr** [kiwix/libkiwix#410]
It was the case before and as been changed by this commit : https://github.com/kiwix/kiwix-lib/commit/286fbba9f6b6921a23305bc9dd370334e42d930e

The `CI` workflow is only used to check that the code is valid (it compiles it and test it), nothing is publish or keep. (And so, it should be called `Check`)
It "publish" only code-coverage reports and comment on the PR (who make sens only in a PR context).

The workflow is that any changes must pass by a PR.
We want to check that the PR is valid. If the PR is on a branch in a fork repository, there is not push on our side and the CI is not launch.

Running the Check on master is useless as it produces nothing and if there is something wrong in the code, what is wrong is that the code should never has been push in first instance. It add no benefice.

**Comment by rgaudin** [comment]
Agrees with the approach. Only concern is whether the *CI badge* will reflect the current status of master. It looks like it will as it aggregates the workflows that gets merged (I think) but I can't say for sure.

**Comment by mgautierfr** [comment]
On top of that, the `Package` workflow should (ideally*) not run on PR.
Building a package of a pull request is useless.
We want to build package for master (dev/test packages) and tag (release).

[*] But we also want to test that change on how we build package is still ok, before merging it into master. :man_shrugging:

**Comment by kelson42** [comment]
We need to run on push on master.

Maybe we need to do what is recommended here? https://github.community/t/how-to-trigger-an-action-on-push-or-pull-request-but-not-both/16662/2

Pun @veloman-yunkan

**Comment by mgautierfr** [comment]
> We need to run on push on master.

Why ?

**Comment by kelson42** [comment]
Because otherwise I know no better way to know if `master` pass the CI properly, which is important to me.

I don't forget about this ticket, I want to bring it through.

**Comment by kelson42** [comment]
> On top of that, the `Package` workflow should (ideally*) not run on PR.
> Building a package of a pull request is useless.

If you add a dependence, or use a feature which is only available in a new version of a dependence. The `Package` workflow will tell you if there is a problem... otherwise you will detect this later only after merging to master.
