### ISSUE TITLE
Kiwix-serve random feature returns partly broken URLs

### ISSUE THREAD

**Issue by kelson42** [kiwix/libkiwix#441]
With a ZIM with the article `?_(album_de_Nena)` from WPFR. The random button returns the following URL: http://localhost:8080/wikipedia_fr_articles_2019-07/A/?_(album_de_Nena) and it should return http://localhost:8080/wikipedia_fr_articles_2019-07/A/%3F_(album_de_Nena).

**Comment by kelson42** [comment]
@mgautierfr I would need a full analysis of the problem/fix here.

**Comment by veloman-yunkan** [comment]
This issue seems to be a special case of #775
