### ISSUE TITLE
Kiwix-serve suggestion does not work from search results page

### ISSUE THREAD

**Issue by maneeshpm** [kiwix/libkiwix#496]
When we type anything in the search box from the search results page, we do not get suggestions. This is probably because the request is generated using the wrong parameters.
```
...
arguments :
 - content : 'search'
 - term : 'twin city'
Parsed : 
full_url: /suggest
url   : /suggest
acceptEncodingDeflate : 1
has_range : 0
is_valid_url : 1
.............
** running handle_suggest
Response :
httpResponseCode : 404
...
```
As seen in the log, the generated url takes the `content` parameter from the search page url(localhost:8080/**search**?content="foo"&pattern="bar"), hence the `content` parameter is invalid. 

```
..
arguments :
 - content : ''
 - term : 'twin'
Parsed : 
full_url: /suggest
url   : /suggest
acceptEncodingDeflate : 1
has_range : 0
is_valid_url : 1
.............
** running handle_suggest
Response :
httpResponseCode : 404
...
```
As seen above, This does not work from the main page as well since the url (localhost:8080/) does not have any content.

**Comment by kelson42** [comment]
I suspect a duplicate of https://github.com/kiwix/kiwix-tools/issues/446

**Comment by kelson42** [comment]
@maneeshpm This is a regression which has probably been introduced recently, but impact is quite bad indeed. Do you think you could quickly fix it?

**Comment by maneeshpm** [comment]
@kelson42 Since I have already spotted the problem and have a patch in mind. I will get started on it.

**Comment by kelson42** [comment]
@maneeshpm Thank you

**Comment by maneeshpm** [comment]
@kelson42 Unlike search, suggestions does not work from the main page as well. But that is a different issue.

**Comment by kelson42** [comment]
@maneeshpm yes, this is conceived to be multizim and this does not work. But this taskbar will disappear from the welcome page this week, so no worry.
