### ISSUE TITLE
We should avoid to search again from beggining when changing search page.

### ISSUE THREAD

**Issue by mgautierfr** [kiwix/libkiwix#509]
From kiwix/kiwix-tools#92 

>Context: every time you click for 25 more search results, it costs you 30-60 seconds or sometimes much more. So serious teachers and serious students would like to see the first 100 results all on one page (or possibly even a much larger number) to avoid bureaucracy, if at all possible!

Every search request in `kiwix-serve` leads to a totally new search.
However, when a user is searching a content and looping through search pages, the search is always the same, only the results range is changing.
We should store the search results and only get new results from the same search instead of creating a new search each time.

It is not a simply thing to do because we need, at least, to store some kind of user session, to associated a search object to a series of search request.

**Comment by maneeshpm** [comment]
@mgautierfr Now that we have a better idea of how the API in libzim is going to look like, we can start formalising the caching mechanism here. 
To me, it seems like we will be storing 3 different caches:
- `zim::Searcher` for full text db
- `zim::Search` for full text search
- `zim::SuggestionSearcher` for title db. We might want a cache for `zim::SuggestionSearch` which will help to develop #242 , but that's a task for later.

Thinking about the cache size of each type to keep alive is a bit difficult. It depends on the capacity of the host, user preferences like how many archives will the user depend on in a given session etc 
Once we iron out these details, I believe implementation will not be very difficult. We already have a thread-safe LRU cache [template](https://github.com/openzim/libzim/blob/master/src/concurrent_cache.h) in libzim which we can extend here.

**Comment by kelson42** [comment]
@mgautierfr I think it would be great to get an agreement with @maneeshpm about how to proceed here, technically said.

**Comment by mgautierfr** [comment]
I agree with @maneeshpm, implementation should not be complicated.
The question is more on what we store and how (for how long) ?
I would like to mention that we have a kind of cache for reader implemented in the library (which serve as source for the server). But there is no limit there.
It would be nice to homogenize this a bit.

- `Reader`/`Searcher`/`SuggestionSearcher` should probably follow the same rule. They are base objects and the total number will be somehow relative to the number of zim file to serve. We could have a relatively "large" limit.
- `Search` and `SuggestionSearch` are however "final" objects. They will probably not live long and we should have small limit here (1 or 2).

A dumb rule would be :
- Set the default cache size for `*er` to something like 10% of the number of zim (with a minimum a 1).
- Set the default cache size for `Search*` to 2.
- Allow setting it using env variables as it is done for libzim.

Then we see how it is working and we decide if we change this.
