### ISSUE TITLE
Clicking quickly many times on random crashes kiwix-serve for Windows

### ISSUE THREAD

**Issue by kelson42** [kiwix/libkiwix#512]
From https://github.com/kiwix/kiwix-tools/issues/435

> Happens with an old version of kiwix-serve.exe from 2019, and with 3.1.2 downloaded today. In fact, the newer version is even worse, as it tends to repeat the same articles much more frequently, and if you hit the dice "too fast", it tends to hang the server.

**Comment by kelson42** [comment]
@mgautierfr Might that be that this is an other symptom of the same problem like #515?

**Comment by kelson42** [comment]
@OscarL Let us know quickly - if possible - if this fixes your problem. We would like to make a new release only with this fix ASAP.

**Comment by OscarL** [comment]
Downloading the test binaries right now. Will report back as soon as possible!

**Comment by OscarL** [comment]
@kelson42: Alright... after abusing the dice button with several .zim files (sizes: small, medium, huge), the test binaries (from `kiwix-tools_win-i686-3.1.2-5-rc1.zip`) kept working without any negative side-effects!

Thanks to all of you for your work. It is really appreciated!
