### ISSUE TITLE
Kiwix Serve freezing on RPI with a lot of ZIM files

### ISSUE THREAD

**Issue by wsteven-son** [kiwix/libkiwix#513]
Hello, I am running Kiwix server on an Unbuntu armv7l. The server works great, then randomly will spike CPU usage to 300%+ and will render the application unusable until I restart the application in the terminal.

Notes: 
I am running multiple ZIM files
Happens randomly while the server is being used as well as overnight when the server is not in use
Other process not related to Kiwix continue to run (other LAN servers), but Kiwix freezes until restarted

My Kiwix version is 3.1.2

Thanks

**Comment by Popolechien** [comment]
Ran a config with 11 or so files: 

```
"youscribe_fr_audiobooks.fr",
"cest-pas-sorcier_fr_all.fr",
"dicoado_fr_all_maxi.fr",
"jaimelire_fr.fr",
"jamy_fr_all.fr",
"gutenberg_fr_all.fr",
"youscribe_fr_primaire.fr",
"vikidia_fr_all_maxi.fr",
"wikipedia_fr_all_maxi.fr",
"wiktionary_fr_all_maxi.fr",
"wiktionary_fr_app_maxi.fr",
"education-et-numerique_fr_all.fr"
```

Both Raspberry 3B+ and 4B will freeze after a couple of minutes and return a 504 error.

**Comment by holta** [comment]
Just FYI 504 Gateway Timeout Errors are reminiscent of https://github.com/kiwix/kiwix-tools/issues/345 from a year ago?

**Comment by kelson42** [comment]
@holta We are looking currently to understand/fix #513 and #515

**Comment by mgautierfr** [comment]
Please test with binaries in http://tmp.kiwix.org/kiwix-tools_3.1.2-5/

**Comment by kelson42** [comment]
@wsteven-son let us know quickly - if possible - if it fixes your problem. We would like to make a release only with that fix.

**Comment by wsteven-son** [comment]
@kelson42 Working on building the system with identical parameters so that I can reproduce the bug. Once I reproduce I will test with kiwix-tools_3.1.2-5/

**Comment by kelson42** [comment]
@wsteven-son would be really better to just test the binary. Otherwise you will have to rebuild a special branch of libzim first.

**Comment by wsteven-son** [comment]
@kelson42 Just test the binary for basic functionality?

**Comment by kelson42** [comment]
@wsteven-son test that you can not reproduce the bug you first reported.

**Comment by wsteven-son** [comment]
gotcha, on it. Will report back

**Comment by kelson42** [comment]
@wsteven-son Any finding?

**Comment by kelson42** [comment]
Seems to be fixed told with latest libzim told me @mgautierfr.
