### ISSUE TITLE
OPDS endpoint for categories

### ISSUE THREAD

**Issue by rgaudin** [kiwix/libkiwix#518]
In order to improve ZIM files filtering on readers, we need to maintain a centralized list of *Categories* to which ZIM files are attached to. This has been mentionned in [kiwix-lib#130](https://github.com/kiwix/kiwix-lib/issues/130) and [kiwix-desktop#193](https://github.com/kiwix/kiwix-desktop/issues/193).

The Categories list will start with the followings and should support internationalizations (`en` translations bellow).

* `gutenberg`: `Gutenberg`
* `phet`: `PhET`
* `psiram`: `Psiram`
* `stack_exchange`: `Stack Exchange`
* `ted`: `TED`
* `vikidia`: `Vikidia`
* `wikibooks`: `Wikibooks`
* `wikinews`: `Wikinews`
* `wikipedia`: `Wikipedia`
* `wikiquote`: `Wikiquote`
* `wikisource`: `Wikisource`
* `wikispecies`: `Wikispecies`
* `wikiversity`: `Wikiversity`
* `wikivoyage`: `Wikivoyage`
* `wiktionary`: `Wiktionary`

**Comment by kelson42** [comment]
Discussing about this feed with @Popolechien and @rgaudin, it appears that the feed should probably not offer categories for which there is no ZIM available. @veloman-yunkan This is already the case in your PR? Should I open a new ticket?

**Comment by veloman-yunkan** [comment]
@kelson42 I don't think that we need another ticket for that.
