### ISSUE TITLE
inject_root_link() is being called a bit overzealous

### ISSUE THREAD

**Issue by IMayBeABitShy** [kiwix/libkiwix#524]
Hello everyone,

I've encountered a bug for which I believe the way `inject_root_link()` is being called to be responsible for. See the following report for details.

# Observed behavior

I've created a ZIM file which includes 3rd party javascript files (`brython.js` and `brython_stdlib.js`). Strangely, loading `brython_stdlib.js` from the ZIM failed in a syntax error depending on which device served the ZIM file (via `kiwix-serve`). Initial debugging concluded that the file was changed to include `'<link type="root" href=""></head>` instead of `<head>`. This would normally be fine, but this html snippet is apparently part of a string and the use of `"` instead of `'` caused the string to be ended too soon. The details here aren't kiwix's fault, but kiwix shouldn't decorate a `.js` file anyway, which brings us to this bug.

# Expected behavior

A `.js` file shouldn't be decorated to begin with.

# Further debugging results

I believe I've tracked this bug down to line 263 of `server/response.cpp`. Introduced in https://github.com/kiwix/libkiwix/commit/c557bb271be10d1c865ea80e979109461ec159e4, the function `inject_root_link()` is called as part of `ContentResponse::create_mhd_response()`. This call happens outside of the `if (contentDecorationAllowed())` check, which causes the injection to happen regardless of the file's mimetype.

# Proposed fix

Moving the current line 263 to be below the current line 265 *should* fix this issue. I would make a PR to fix this, but I have neither any trust in my C++-skills nor a working build environment, so it'd be a blind fix at most.

**Comment by kelson42** [comment]
@IMayBeABitShy Could you please give the full header like it is in the zim? the one you get from kiwix-serve? The HTML you expect? Your version of libkiwix?

**Comment by IMayBeABitShy** [comment]
Oh, sorry I forgot to include that information:

> Your version of libkiwix?

It's a roughly 5 days old build from source. Note that this issue doesn't happen using the older `3.1.2-4` release from the website.

> The HTML you expect?

That's the problem: It's a javascript file that get's modified, not a HTML file. Basically, the javascript file contains a string with a HTML snippet. This HTML snipped gets modified, but the HTML attributes added by kiwix use `"` which is also the string delimiter used by the javascript file, thus ending the string too soon and causing a syntax error. To my understanding, this happens because `inject_root_link()` gets called outside of the `contentDecorationAllowed()` check, which would be responsible for ensuring only HTML files get modified. The modification process seems to just modify the first occurrence  of `</head>`, which happens to be part of a string the javascript file.

You can find the included javascript file [here](https://brython.info/src/brython_stdlib.js). Note that loading it requires [this script](https://brython.info/src/brython.js) to be loaded first.

> Could you please give the full header like it is in the zim? the one you get from kiwix-serve?

I'm not sure how to get the header directly from the ZIM. Still, the response headers from kiwix-serve (see below) match what I expected. 

```HTTP
HTTP/1.1 200 OK
Connection: close
Content-Length: 923781
Content-Type: text/javascript
Access-Control-Allow-Origin: *
ETag: "1620986140304985215/cz"
Cache-Control: max-age=2723040, public
Content-Encoding: deflate
Vary: Accept-Encoding
Date: Fri, 14 May 2021 09:55:50 GMT
```
