### ISSUE TITLE
kiwix-search suggestion does not work in absence of Xapian index

### ISSUE THREAD

**Issue by maneeshpm** [kiwix/libkiwix#532]
Currently, in the absence of a Ft index `Searcher::suggestion` does not work. This is because of the following:
- `Searcher::add_reader` does not add the reader if it does not have an ft index. For suggestion search, this is not important because we use the title index anyway. This `add_reader` logic needs to be changed.
- In the absence of Xapian index, zim index should be used ideally(using `zim::Archive::findByTitle`). But this creates a new issue of converting the obtained results into `_Result`. Searcher `Result` uses the new `zim::SearchResultSet` internally which is based on `Xapian::MSet`. Even if we use a method similar to `Reader::searchSuggestion` that is based on `findByTitle(<title prefix>)`, we need a method to convert the result into `zim::SearchResultSet`. 
- We already have the method `Reader::searchSuggestionsSmart` which we use in kiwix-serve to generate suggestions that already performs this fall back properly. But having several methods in different classes for the same purpose of getting suggestions seems odd. We should be able to do this via `Searcher::suggestion` itself.

Some of these complications can be addressed in #430, but others still seem a bit unclear to me. 
The easy way around is using `Reader::searchSuggestionsSmart`, but this check and the corresponding handling of result has to be done by the user.

**Comment by maneeshpm** [comment]
This will most probably get implemented in libzim. Refer discussion on kiwix/kiwix-tools#134 .

**Comment by mgautierfr** [comment]
This issue should be moved in libzim as this is where we will implement it. (We will remove `Reader` and `Searcher` in libkiwix).

---

I'm not totally decided on this (@veloman-yunkan may have a better idea) but :

We probably should have a specific API for suggestions (as it is made in current libkiwix). This API may use xapian db if available and fallback to `iterByTitle`.
It should return "something" that can be iterable (probably a wrapper on `libzim::SearchResultSet` and `libzim::EntryRange`).
