### ISSUE TITLE
OPDS Icon is limited

### ISSUE THREAD

**Issue by rgaudin** [kiwix/libkiwix#533]
At the moment, most ZIM only include a `Favicon` metadata that is 48px squared due to the requirement in the spec and the fact that kiwix-serve has only ever displayed it.

Some ZIM don't respect it and include different resolution/form-factor.

With the ability to now use higher definition illustrations via the `Illustration` metadata, it's important those are used when available and pertinent. I suppose kiwix-serve might use it for its homepage redesign.

With the global switch to OPDS in readers, it's important that those higher definition images are available through OPDS, to accomodate the platform/reader needs. On a high DPI (retina) display, the 48px is blurry unless scaled down to 24px which is **very small**.

I have no suggestion on how that should be done. The current node reads as:

```xml
<icon>/meta?name=favicon&amp;content=gutenberg_sv_all_2021-05</icon>
```

**Comment by kelson42** [comment]
@veloman-yunkan We really need that to get proper fancy catalogue. Does the libzim7 delivers what is necessary to extend here the OPDS?

**Comment by kelson42** [comment]
@rgaudin @mgautierfr After our discussion of last week, we probably need here - as well - a pixel depth indicator?

**Comment by veloman-yunkan** [comment]
> Does the libzim7 delivers what is necessary to extend here the OPDS?

@kelson42 Not at the moment. I [proposed an enhancement](https://github.com/openzim/libzim/pull/540#discussion_r630801469) earlier.

**Comment by kelson42** [comment]
@veloman-yunkan This has been implmented, but still in review. Any chance to get a libkiwix PR using this new API soon?

**Comment by kelson42** [comment]
The code is now in libzim master.

**Comment by veloman-yunkan** [comment]
@kelson42 @mgautierfr In order to test the fix for this enhancement I will need a ZIM file with multiple illustration entries. How do I create one?

**Comment by kelson42** [comment]
@veloman-yunkan @mgautierfr There should be already one in the https://github.com/openzim/zim-testing-suite ?! I remember we had to make a new release there before merging the Illustration related PR at openzim/libzim.

**Comment by mgautierfr** [comment]
> There should be already one in the openzim/zim-testing-suite 

Not with several illustration entries.

> How do I create one?

Clone openzim/zim-testing-suite, modify the data/scripts, regenerate the zim files, commit everything and make a PR.
There is no automated process for now.

**Comment by veloman-yunkan** [comment]
> Clone openzim/zim-testing-suite, modify the data/scripts, regenerate the zim files, commit everything and make a PR.

But is there a tool that can create a ZIM file with several illustration entries? Or a workaround?

**Comment by rgaudin** [comment]
just call addIllustration() multiple times with different sizes

**Comment by veloman-yunkan** [comment]
> just call addIllustration() multiple times with different sizes

This is not acceptable as long it requires a custom build of `zimwriterfs` . Test data must be created in a reproducible way.

**Comment by rgaudin** [comment]
Hum, I think I understand what your problem is here ; please confirm:
- libkiwix is not using the new test files repo.
- most tests zims from this repo are not reproducible. There are present, but we don't have the source code which created them.
- Only `corner_cases.zim` is reproducible (`create_corner_cases_zim_file` shell script)
- `corner_cases.zim` is built using zimwriterfs at the moment so until zimwriterfs can write multiple Illustrations, it can't be used to create appropriate test.

You could have been a little more explicit 😅

Would it make sense to create an additional many-illustrations zim file (using libzim, not zimwriterfs) just for this use case ?
