### ISSUE TITLE
Question: How to count the number of ZIM files (or query results) on kiwix-serve's new welcome page?

### ISSUE THREAD

**Issue by holta** [kiwix/libkiwix#547]
What's the best way to count the number of ZIM files (query results) on the kiwix-serve welcome page?  That used to be straightforward to find out, by very rapidly loading the full page, and then counting (or at least guesstimating!) the number of ZIM files on that page.

But as a result of PR #534, the new kiwix-serve welcome page loads VERY slowly (as a result of AJAX-like incremental loading, as you progressively scroll further and further down the page).

So guesstimating the number of ZIM files (and things like Ctrl-F) are suddenly much more difficult.

As a Result: could this number (the total number of ZIM files returned) ideally be displayed somewhere, perhaps on top of the kiwix-serve welcome page ?!  Ideally this would be similar to the way Google searches...always show a line like:

   "About 17,700 results (0.35 seconds)"

Refs: #517, #519, #531

**Comment by kelson42** [comment]
@holta The machine readable library API is the OPDS feed, see https://wiki.kiwix.org/wiki/OPDS
