### ISSUE TITLE
PR #534 Question: How does one use Cross-ZIM Full-Text search?

### ISSUE THREAD

**Issue by holta** [kiwix/libkiwix#548]
What's the best way to do Cross-ZIM Full-Text / FT search (across all installed ZIM files) after PR #534 is merged ?

Understandably, moving this lesser-used functionality from the top of kiwix-serve's welcome page (to a new location?) appears to be part of the design — as very slow searches are not the common case (nobody should expect offline searching across ZIM files to be fast as of 2021!)

But at the same time: some teachers/librarians very much do depend on occasionally using this (Cross-ZIM search, both Title search and Full-Text search when available) for occasional-but-important "reference" deep searching.  For example during research projects, history classes, media literacy education, fact-checking, etc.

Conclusion: whether or not Cross-ZIM Full-Text search is prominently advertised (or intentionally rather hidden) what is the recommended way for advanced students/teachers/librarians to find and use this advanced feature?

Refs: #519, #547

**Comment by kelson42** [comment]
Multizim is broken for the moment, see #479.
