### ISSUE TITLE
Kiwix-serve, simplify specifying of multiple .zim files on the run command

### ISSUE THREAD

**Issue by eroyee** [kiwix/libkiwix#552]
A feature suggestion:

When running kiwix-serve for multiple .zim files in a single directory it would be useful to be able to simply specify something like path+to+directory/(*.zim) rather than have to specify each individual path+file as part of the run command. 

This feature would be further enhanced if kiwix-serve periodically checked the directory contents and updated the landing page with links for content files that were added or removed from that directory.

I realise there's a use-case for being able to specify individual files in different locations, but perhaps this could be invoke with a switch?

Apologies if this has already been implemented or requested, I have looked but cannot immediately find anything to this end.

Thanks.

**Comment by kelson42** [comment]
Alreqdy works like you describe and with the globbing, see https://linuxhint.com/bash_globbing_tutorial/.
