### ISSUE TITLE
Kiwix Serve filters on welcome page should be kept

### ISSUE THREAD

**Issue by kelson42** [kiwix/libkiwix#557]
Steps:
* Choose a few filters
* Click on a content and surf
* Comeback to the homepage

I get:
* The default filter

I want:
* The filters like I left them

**Comment by MananJethwani** [comment]
@kelson42 should I use local storage for this feature? Or any better way you have in mind

**Comment by kelson42** [comment]
@MananJethwani No, cookies please. Take care that the URL is always in sync.

**Comment by MananJethwani** [comment]
will create a separate PR soon
