### ISSUE TITLE
Do not expose mustache (and other depedency/tools) in public headers.

### ISSUE THREAD

**Issue by mgautierfr** [kiwix/libkiwix#564]
The public header otherTools.h include mustache.h (https://github.com/kiwix/libkiwix/blob/master/include/tools/otherTools.h#L27).
By doing thing, we defacto make mustache a direct dependency of projects using libkiwix.
If somehow `otherTools.h` is include by a project foo. The mustache header must be present even if foo never use mustache.
This is what happen here https://github.com/kiwix/kiwix-desktop/runs/2904840393?check_suite_focus=true (PR https://github.com/kiwix/kiwix-desktop/pull/656) where the compilation of kiwix-desktop fails as mustache.hpp is not present.

We must not include header of our private dependencies in public our headers.

More than just cleaning the mustache inclusion (and other tools, we also include `zim.h` and we should not), we should probably carrefully select what helper function are part of our API and move all other tools private.

**Comment by legoktm** [comment]
> More than just cleaning the mustache inclusion (and other tools, we also include zim.h and we should not),

In the Debian package we currently depend on:
```
 libzim-dev (>= 6.0.0),
 libicu-dev,
 libpugixml-dev,
 libcurl4-gnutls-dev,
 libmicrohttpd-dev
```
since those are exposed as part of the public API. These are also listed in kiwix.pc.
