### ISSUE TITLE
[SERVER] Do not use query to convey the filters of the main page.

### ISSUE THREAD

**Issue by mgautierfr** [kiwix/libkiwix#565]
The main page of the server now have a filter feature.

Of course we need to "expose" the filters in the url. This allow the user to copy/paste the url and keep the applied filter.

But the querystring (the string after `?`) is part of the url send to the server. It means that urls `library.kiwix.org`, `library.kiwix.org?lang=foo` and `library.kiwix.org?lang=bar` are three different urls, browser must send them to the server. This is a pity as the server don't care about the querystring here and always send back the same content.

We could use the hash value (the string after `#`) to store the active filters. The hash value is not send to the server. It means that the three urls, would be "reduce" to `library.kiwix.org`. The browser could detect they are "the same" and cache the content. In the same time, the browser (and our js) will know that urls are not the same and will correctly handle that (change the url in the address bar, add a history state, ...).

**Comment by kelson42** [comment]
@mgautierfr Wich concrete problem does this ticket proposes to fix?

**Comment by mgautierfr** [comment]
> It means that urls library.kiwix.org, library.kiwix.org?lang=foo and library.kiwix.org?lang=bar are three different urls, browser must send them to the server. This is a pity as the server don't care about the querystring here and always send back the same content.

The three requests will be sent to the server which will return exactly the same content as the filtering is made of the client side.

**Comment by kelson42** [comment]
@mgautierfr This ticket is relevant because the language filter is done in Javascript. If it would be done in C++ that would invalidate this ticket right? In such a scenario, It seems #750 invalidates this ticket to me.

**Comment by mgautierfr** [comment]
There is two things:
- The translation of the frontend. #750 is about this.
- The filtering of books, based on a language selected by the user.

When user go to `library.kiwix.org`, `library.kiwix.org?lang=foo` or `library.kiwix.org?lang=bar`, the server don't care about the query string (`lang=foo`) and always return the same frontend client 
(This is not **exactly** the same as the frontend is translated, but is is orthogonal to this issue).
Then the frontend parse the url and then do a query to the catalog using the `lang` : `library.kiwix.org/catalog/search?lang=foo` (and then the server care about the query string and return different content)

As at the first step, the server always send the same content, we must use the same url. If we use a different url, browser thinks it is a different content and do several requests.
As the `lang` is used only by the frontend, we can/should keep it in the hashvalue.
(Here we speak about `lang` filter, but it is the same for the category or the textual query)

**Comment by kelson42** [comment]
After an IRL discussion, there is an agreement we should do it.
