### ISSUE TITLE
New/Update Illustration API

### ISSUE THREAD

**Issue by kelson42** [kiwix/libkiwix#566]

**Comment by mgautierfr** [comment]
Is this fix by https://github.com/kiwix/libkiwix/pull/560 or you expect something else ?

**Comment by kelson42** [comment]
@mgautierfr I don't think so, we need to expose the ability in the libkiwix to get the list of illustration, choose an illusatrion by width x height x pixel depth. Or is that already made? Or does something additional is not needed at all (user should use libzim classes directly)?

**Comment by mgautierfr** [comment]
We plan to remove the `Reader` wrapper from libkiwix. So on cpp side it is a bit counter productive to add a method to a class we will remove just after.
But we want to update the OPDS stream to list the different sizes and allow the kiwix-serve to serve the illustration (#577)

**Comment by kelson42** [comment]
So do we need to have this ticket to secure that @automactic will be able to retrieve many illustrations?

**Comment by mgautierfr** [comment]
As we will drop the reader wrapper (#430) @automactic is better to start directly use the libzim API.
