### ISSUE TITLE
How to make a search on tags? Same question about filter by tags?

### ISSUE THREAD

**Issue by kelson42** [kiwix/libkiwix#573]
With a "search", I mean not only search on title, description but in tags as well.

For the filter, it would be: given a tag, list all content having it.

See #572

**Comment by mgautierfr** [comment]
What are you speaking about ?

- the cpp api,
- the opds api,
- the search on the front page server ?

**Comment by kelson42** [comment]
Sorry was indeed umclear, I meant from the API.

**Comment by veloman-yunkan** [comment]
> Sorry was indeed umclear, I meant from the API.

@kelson42 Which API - C++ or OPDS?

**Comment by kelson42** [comment]
the rest api

**Comment by kelson42** [comment]
@veloman-yunkan any feedback here?

**Comment by veloman-yunkan** [comment]
@kelson42 For the OPDS catalog API v2, the following query does the job:

```
/catalog/v2/entries?q=tag:tagname
```

Tags with values (those of the form *tagname:tagvalue*, e.g `_pictures:no`, `_category:youtube`) aren't handled correctly when the value of the tag is specified along with the name of the tag, but that shouldn't be difficult to fix.

Regarding the title of this issue - what's the difference between searching and filtering?

**Comment by kelson42** [comment]
@veloman-yunkan Thx for the answer on the filter part. The search part is when someone makes a free text search for example by typing "science" in kiwix serve welcome page search box. Currently it searches this pattern in the titles, descriptions (and I believe filenames). I ask myself if it would not be a good idea to search this pattern in the zim tags as well? If this is already done or somehow already achevable,

**Comment by kelson42** [comment]
@veloman-yunkan I have thought twice (and even more) and I would like - if nobody opposes - to include tags in the "free text" search (which currently searches "only" in title, description and filename). Would you be able to do that?

**Comment by veloman-yunkan** [comment]
> The search part is when someone makes a free text search for example by typing "science" in kiwix serve welcome page search box.

@kelson42 This needs a clarification.

1. In the currently released version of libkiwix (which presently runs at https://library.kiwix.org), the search on the welcome page works via the `/search` endpoint (which returns a complete HTML page with search results).
2. In the rehauled/master version of libkiwix, the search on the welcome page works via the `/catalog/search` endpoint which returns an OPDS XML result (and the HTML is rendered from it in the front-end). **To the best of my understanding this is the same as filtering**.

Taking into account your next sentence

> Currently it searches this pattern in the titles, descriptions (and I believe filenames).

I conclude that you were referring to 2. (i.e. `/catalog/search`), which means that we should not distinguish between searching and filtering.

> @veloman-yunkan I have thought twice (and even more) and I would like - if nobody opposes - to include tags in the "free text" search (which currently searches "only" in title, description and filename). Would you be able to do that?

So, if we are speaking about filtering the catalog, then including tags in the filter is not a problem.

**Comment by mgautierfr** [comment]
>- In the currently released version of libkiwix (which presently runs at library.kiwix.org), the search on the welcome page works via the /search endpoint (which returns a complete HTML page with search results).
>- In the rehauled/master version of libkiwix, the search on the welcome page works via the /catalog/search endpoint which returns an OPDS XML result (and the HTML is rendered from it in the front-end). To the best of my understanding this is the same as filtering.

This is two different searches. The first one is fulltext search returning articles. The second is a search of zim files themselves.

> I would like - if nobody opposes - to include tags in the "free text" search (which currently searches "only" in title, description and filename). Would you be able to do that?

I'm not opposed to that but it should be done carefully.
We don't want to search in "hidden" tags (`video:yes`). We don't want to return all zim files when user searches for "Video" or "yes".

**Comment by kelson42** [comment]
Thx @mgautierfr for your last comment, it summarizes my opinion of the moment. I will close this ticket as the primary questioning is answered and will open a new ticket to integrate tags to search... a ticket we could keep a bit open before inplementing to let the idea maturing properly.
