### ISSUE TITLE
Kiwix Serve welcome page Download overlay

### ISSUE THREAD

**Issue by kelson42** [kiwix/libkiwix#579]
To propose, based on the metalink XML:
*  Magnet links
* Hashes
* Bittorrent links
* Usual HTTP download link

This should be displayed if metalink is available and if someone clicks on a tile download button.

The parsing of the metalink file should be smart, ie. we download/parse only the part of interset in the XML and then stops. We are not interested in all the hashes.

**Comment by MananJethwani** [comment]
@kelson42 we can have a modal pop up when someone clicks the download button  where we can show these multiple links....would be much cleaner

**Comment by kelson42** [comment]
@MananJethwani yes, this is what I mean I believe.
