### ISSUE TITLE
Limited to 48x illustration

### ISSUE THREAD

**Issue by rgaudin** [kiwix/libkiwix#580]
With the new libzim Illustration API, we are now able to produce multi-illustration ZIMs.

Currently, when retrieving the Illustration (still called favicon here), we only fetch the default (thus `48`) version, whatever is available in the ZIM.

https://github.com/kiwix/libkiwix/blob/60f0f81286dc1364369d818b2acc18d8fc7f178a/src/tools/archiveTools.cpp#L72-L82

In the past, with the old `-/favicon` Entry, **although not respecting the spec**, one simple trick for Zim creator was to write a larger image there so that when displayed by kiwix-serve in the homepage, it wouldn't look ugly on high-density screens…

With the new API requiring to input size explicitly, it feels wrong (although it's basically same as before) to put a larger than 48px-large illustration in the `48` slot. But if we don't, icon will be blurry in kiwix-serve on high-density screens…

@kelson42, what do you think?

**Comment by kelson42** [comment]
I don't think we put larger favicon in the ZIM files. The openZIM specs says it has/had to be 48x48. Therefore I believe I don't understand this ticket.

**Comment by rgaudin** [comment]
I think you understand the ticket 😀

I just want us to agree that either we continue not respecting the spec (in a more flagrant manner) or we decrease rendered quality of icons in this case.

Additional possibility is to implement a smarter `getArchiveFavicon()` in libkiwix.

**Comment by kelson42** [comment]
We should definitly respect the spec.

**Comment by mgautierfr** [comment]
We should respect the spec yes.
But maybe the spec also have to be adapted. Why the 48px size ? If we were putting higher res icon since a long time maybe 48x48 is too small.
