### ISSUE TITLE
getArchiveFavicon not returning Illustration

### ISSUE THREAD

**Issue by rgaudin** [kiwix/libkiwix#581]
This is very new so it might be a mistake on my hand but I created Zim files with either a single `48` Illustration or multiple illustrations and in all those cases, kiwix-serve returns nothing for the `/meta&name=favicon`.

Could some else please test it and maybe confirm?

**Comment by kelson42** [comment]
@rgaudin Can you maybe provide a test zim?

**Comment by rgaudin** [comment]
My bad, I typed `2021-06-07` instead of `2021-07-07` in my script and got a month-old build ! 

Sorry about that.

**Comment by rgaudin** [comment]
Works
