### ISSUE TITLE
Add ability to filter by tags in Kiwix-serve welcome page

### ISSUE THREAD

**Issue by kelson42** [kiwix/libkiwix#582]
It is possible via /catalog/v2/entries?q=tag:tagname but the exact workflow is still to be decided.

What is sure is that each displayed tag should be a link to allow a filter by tag.

But we probably don't want an additonal tag filter select box (and I would not know how to populate it anyway).

**Comment by Popolechien** [comment]
@kelson42 I'm seeing the advisory board on Friday and several of them would have meaningful input there. My only question is: would these tags be included at CMS-level (ie later this year), or when creating the recipe (e.g. zimfarm, where there is a "tag" entry, which we could then deploy fairly soon)?

**Comment by kelson42** [comment]
@Popolechien Tags are ZIM metadata. As such are part of the ZIM specs, handled at the scraper level, part of the ZIM file. But like all other ZIM metadata, it will be possible to overwrite then with the CMS.... when this one will be ready.

**Comment by MananJethwani** [comment]
@kelson42 we can have a dropdown in search bar only where as soon as a user clicks to type they get a  suggestion -> `search by tags <highlighted>tags:<highlighted>` 
and if the user selects this option we will automatically add `tags:` to the search bar.

**Comment by juuz0** [comment]
There is a problem (or a good thing?) with using `/catalog/v2/entries?q=tag:tagname`. 
Consider two tags : `science` (this is not on any book, but just for example if two tags started with the same word) and `science in the bath`.
If we use `?q=tag:science`, this will show **every** book whose tags start with **science**, thus **science in the bath** also.
![image](https://user-images.githubusercontent.com/26814569/153425559-ffcc7392-9777-4972-8099-caac38540d83.png)

There's an other way to get books specified by tags (found from `test/opds_dumper.cpp`) :
Use `/catalog/v2/entries?tag=tagname`

This will show exact results only
For tag = "science"
![image](https://user-images.githubusercontent.com/26814569/153428224-3b7d469d-076f-463e-bf3c-4fe4e2988a82.png)

For tag = "science in the bath"
![image](https://user-images.githubusercontent.com/26814569/153428559-bfd63655-3768-4ca4-a3fb-ba6c4d78f6a7.png)

**Comment by kelson42** [comment]
@juuz0 Your comment is really interesting.

First the `tag=...` is exactly what is needed here. So we can reduce the discussion to how this ability to filter should look like.

Then your remark about `q=tag:...` would be IMO really appropriate in #599

**Comment by juuz0** [comment]
> So we can reduce the discussion to how this ability to filter should look like.

Indeed, I don't have much idea here. Earlier I thought, filling the search box with "tag:tagname" should work but if we are using `tag=...` here then IMO there should be some other way to tell the user which tagged has been added (and a way to remove the filter also). Do you have ideas?

**Comment by kelson42** [comment]
@juuz0 I don't have a definitive opinion but for the moment I think of:
* Making the tags clickable
* Display the applied tag filters in a form of badges beside the selectbox
* Clickin on a badge woukd remove a tag filter
