### ISSUE TITLE
Kiwix-serve welcome page doesn't account for --urlRootLocation

### ISSUE THREAD

**Issue by veloman-yunkan** [kiwix/libkiwix#589]
When kiwix-serve is started with the `--urlRootLocation` option, the welcome page is broken:

1. Icons in the book tiles cannot be loaded
2. The preview link is incorrect

**Comment by kelson42** [comment]
@MananJethwani Can younplease have a look? I suspect that this regression has been introduced recently with your work around new welcome page.

**Comment by MananJethwani** [comment]
working on it
