### ISSUE TITLE
Smarter default filter

### ISSUE THREAD

**Issue by rgaudin** [kiwix/libkiwix#594]
On first visit of kiwix-serve, the language filter is set to the language of the browser.

I think most frequently than not, the library might not have any content for that filter, offering a deceptive first contact.

Ideally, if the library has no content for that browser language, it should fallback to no language filter.

Cookie behavior is fine IMO.

**Comment by kelson42** [comment]
@Migh be a good idea that if no content in browserlanguage, then just don't apply any language filter

**Comment by kelson42** [comment]
@rgaudin Please have a look and let us know if this looks good to you.
