### ISSUE TITLE
All Kiwix Serve API end-points should serve HTTP responses with ETAG

### ISSUE THREAD

**Issue by kelson42** [kiwix/libkiwix#598]
To the opposite to content request, it seems Kiwix Serve does not serve HTTP responses with ETAG:
```
$ curl -I http://localhost:8080/catalog/search?lang=fra
HTTP/1.1 200 OK
Connection: Keep-Alive
Content-Length: 493
Content-Type: application/atom+xml; profile=opds-catalog; kind=acquisition; charset=utf-8
Access-Control-Allow-Origin: *
Cache-Control: no-cache, no-store, must-revalidate
Date: Sat, 31 Jul 2021 09:11:41 GMT

$ curl -I http://localhost:8080/wikipedia_en_100_mini_2021-06/A/index
HTTP/1.1 200 OK
Connection: Keep-Alive
Content-Length: 9613
Content-Type: text/html
Access-Control-Allow-Origin: *
ETag: "1627722524969251296/c"
Cache-Control: max-age=2723040, public
Date: Sat, 31 Jul 2021 09:15:38 GMT
```

Therefore, no API request is cached and this seems not optimal to me. I propose to have them served with an ETAG, so the HTTP client get a chance to make the appropriate HTTP request to save bandwidth/waiting time. Actually the whole HTTP workflow around ETAG should be supported, see https://developer.mozilla.org/fr/docs/Web/HTTP/Headers/ETag. It should be automated tested and Kiwix Serve welcome page requests should benefit of this improvement.

@mgautierfr @MananJethwani @veloman-yunkan Does that sound appropriate?

**Comment by veloman-yunkan** [comment]
@kelson42 Kiwix server search results are (going to be) more volatile than individual items from served ZIM archives. ZIM archives typically should not change for a running server, while we have a [ticket](https://github.com/kiwix/kiwix-tools/issues/243) for updating the library without restarting the server. What TTL do you propose for responses to search results?

**Comment by kelson42** [comment]
@veloman-yunkan Here is how I see things, and I hope this is correct.

An ETAG is not a TTL or cache expiration value. The ETAGs should be just be a random string indicating if the (requested) content has changed until last time the (very same) request has been done. AFAIK usually this is handled transparently by the browser (component).

Therefore, the only one question left IMO is how many ETAGs and when to change them, considering (like you said properly) that as soon as #243 will be implemented we won't be anymore able to assume that we just need to setup it at the restart of `kiwix-serve`.

I would propose to distinguish two cases:
* API requests which deal with multiple content at once (multizim suggestion/ft searches or catalog related), then each time a new content is loaded/unloaded of kiwix-serve, the ETAG must be changed. Here, one global ETAG would be used.
* API requests which deal with only one content (single suggestion/ft searches or articles content), then we can keep the same ETAG as long as this specific ZIM file is not reloaded. Here, on ETAG per ZIM file.

Does that looks good?

**Comment by veloman-yunkan** [comment]
> An ETAG is not a TTL or cache expiration value. The ETAGs should be just be a random string indicating if the (requested) content has changed until last time the (very same) request has been done. AFAIK usually this is handled transparently by the browser (component).

@kelson42 For an ETAG to make any difference the content must be cached. If a response contains an `Etag` header but also says `Cache-Control: no-cache, no-store, must-revalidate` (like it currently does for search requests) then the client cannot take advantage of the etag if it respects the `Cache-Control` header and doesn't cache the content. On the other hand, taking etags into account is not mandatory. If we allow caching of responses to search requests, nothing prevents the clients from ignoring the etags and assuming that the cached content remains valid until expiration. Etags can be helpful in avoiding to refetch content with expired cache lifetime (though, this is again optional, and works only for browsers that support Etags).

**Comment by kelson42** [comment]
@veloman-yunkan Agree, wee need to change the `cache-control` header as well if we want our etag fix to be effective. Concerning that point, I have been pretty much puzzled by https://github.com/openzim/warc2zim/issues/66 and what we should do at the Kiwix Serve level. Now, I believe that we should at least reduce the overall cache TTL from one month to 24h.

**Comment by kelson42** [comment]
closed in favour of a more general approach, see #650
