### ISSUE TITLE
Integrate tags to free text library search

### ISSUE THREAD

**Issue by kelson42** [kiwix/libkiwix#599]
Following #573, it appears that we would benefit to add tags to the free text search which already includes:
* filename
* title
* description

This would allow more accurate results. That said, we should be carefull to not integrate hidden tags to this search.

**Comment by kelson42** [comment]
@veloman-yunkan I think the need is confirmed now. We shoukd implement it.

**Comment by veloman-yunkan** [comment]
> Following #573, it appears that we would benefit to add tags to the free text search which already includes:
> 
>     * filename
> 
>     * title
> 
>     * description

@kelson42 filename is not included in the general free text search

**Comment by kelson42** [comment]
@veloman-yunkan OK, we will see in the future if this is necesdaty to integrate it.
