### ISSUE TITLE
kiwix-serve does not populate enough cards to scroll on a large screen

### ISSUE THREAD

**Issue by jmontleon** [kiwix/libkiwix#603]
On a 4k screen I get 4 rows of 7 cards. I have 130 zim files loaded and it's impossible to scroll further. In order to see more I have to resize the window (either a bit larger or smaller) to get additional cards to load, and then I am able to scroll.

**Comment by MananJethwani** [comment]
@kelson42 will fix it in few moments...sorry for the bug.

**Comment by MananJethwani** [comment]
@jmontleon I have opened a Pull Request we will try to merge it soon, if you have knowledge on how to compile the code I would like you to test it once. I have around 90 zim files available and in the PR everything seems to work for me.
