### ISSUE TITLE
HTTP 503 when retrieving favicons

### ISSUE THREAD

**Issue by automactic** [kiwix/libkiwix#608]
Sometimes when I am retrieving favicon using urls like `https://library.kiwix.org/meta/meta?name=favicon&content=pets.stackexchange.com_en_all_2021-04` , I got HTTP 503 with the following content:

```
<html>\r\n<head><title>503 Service Temporarily Unavailable</title></head>\r\n<body>\r\n<center><h1>503 Service Temporarily Unavailable</h1></center>\r\n<hr><center>nginx/1.21.0</center>\r\n</body>\r\n</html>\r\n
```

It could be because I am retrieving things too fast, because if I wait for 5s then retry, I will get 200 with a PNG image as content. This is definitely causing me a small amount of headache during development of the kiwix for iOS app, so I just want to clarify if HTTP 503 is expected, under what circumstance should I expect 503 and do we have a rate limit in place?

**Comment by rgaudin** [comment]
@automactic, please not that this endpoint has been removed and is not present anymore in master.
I don't know what's the library.kiwix.org deployment strategy but I suppose it's going to use the next stable kiwix-serve release soon after its introduction (so relatively soon).

A *drop-in* replacement would be `/catalog/v2/illustration/pets.stackexchange.com_en_all_2021-04/?size=48`

**Comment by mgautierfr** [comment]
Note that the illustration link in the OPDS stream will be changed accordingly. So if you use it blindly, you have nothing to change on your side.

**Comment by kelson42** [comment]
@automactic New API (listed in OPDS stream) is https://library.kiwix.org/catalog/v2/illustration/pets.stackexchange.com_en_all_2021-04/?size=48 and seems to work fine. We have done many improvements to avoid returning HTTP 5xx errors and we believe it works now fine. If you still see this kind of error, please reopen this ticket immediatly.
