### ISSUE TITLE
Ladakhi does not appears properly in the list of (kiwix-serve) language

### ISSUE THREAD

**Issue by kelson42** [kiwix/libkiwix#611]
If I load https://mirror.download.kiwix.org/zim/videos/dse-ladak_hi_class-3rd_2021-08.zim with Kiwix-serve, I get this on the Welcome Page:
![image](https://user-images.githubusercontent.com/1029718/131212993-f81aabb4-6550-4c11-819c-bf63c0ae5392.png)

I should see the language listed as "Ladakhi" in place of "lbj".

See more info about Ladakhi language at https://en.wikipedia.org/wiki/Ladakhi_language

**Comment by kelson42** [comment]
@veloman-yunkan I guess that means that the Ladakhi language is not supported by the libicu. Would you be able to confirm please?

**Comment by kelson42** [comment]
@juuz0 If you want to fix that one as well, I believe the solution is to handle our own conversion table in case libicu can not do the job.

**Comment by juuz0** [comment]
@kelson42 Yes, thought the same. Will do

**Comment by juuz0** [comment]
@kelson42 Are there any other known languages with this behaviour?

**Comment by kelson42** [comment]
@juuz0 Do you still plan to fix this bug?

**Comment by juuz0** [comment]
@kelson42 Yep, slid out of my list somehow. By tomorrow for sure

**Comment by kelson42** [comment]
@juuz0 Could you please with a new commit add support to https://en.wikipedia.org/wiki/Dagbani_language. We newly have ZIM files in this language, see https://farm.openzim.org/recipes/wikipedia_dag_all. Here a similar ticket at Zimfarm level https://github.com/openzim/zimfarm/issues/677.

**Comment by juuz0** [comment]
Doing :+1:

**Comment by rishujam** [comment]
How can I navigate to LanguageFragment? Also which fragment ss is shared in the issue

**Comment by kelson42** [comment]
@rishujam Wrong ticket.
