### ISSUE TITLE
Kiwix-serve does not display properly the Ladakhi ISO 639-2 code

### ISSUE THREAD

**Issue by kelson42** [kiwix/libkiwix#612]
If I load https://mirror.download.kiwix.org/zim/videos/dse-ladak_hi_class-3rd_2021-08.zim with Kiwix-serve, I get this on the Welcome Page:
![image](https://user-images.githubusercontent.com/1029718/131212993-f81aabb4-6550-4c11-819c-bf63c0ae5392.png)

Ladakhi does not seem to have the proper ISO 639-2 language code. Actually the Ladakhi language does not have one AFAIK. So I wonder what is wrong here. Probably the ISO 639-3 language code should be displayed here if there is not ISO 639-2 variant. 

See more info about Ladakhi language at https://en.wikipedia.org/wiki/Ladakhi_language

**Comment by juuz0** [comment]
Seems like the icu library doesn't support ISO 639-3 codes yet. For such languages, it will return back the code (`lang`) when `getDisplayLanguage` is found
```
std::string getLanguageSelfName(const std::string& lang) {
  const icu::Locale locale(lang.c_str());
  icu::UnicodeString ustring;
  locale.getDisplayLanguage(locale, ustring);
  std::string result;
  ustring.toUTF8String(result);
  return result;
};
```

A solution is keeping track of such known codes (in json?) and using them if `result` string is same as the passed `lang` string

**Comment by kelson42** [comment]
> Seems like the icu library doesn't support ISO 639-3 codes yet.

This has to be wrong.

**Comment by kelson42** [comment]
There is acatually an other problem which is that the language select box displays "lbj" code is place of "ལ་དྭགས་སྐད་".

For the bad two letters code, part of the problem seems to be in javascript where there is a two letters truncation, which is really wrong.

**Comment by juuz0** [comment]
Thanks for the clarification!

I confused this issue with https://github.com/kiwix/libkiwix/issues/611 

and to confirm your question there, indeed Ladakhi isn't supported yet (and so are many ISO 639-3!)

**Comment by kelson42** [comment]
@juuz0 I had forgotten myself #611, but now this is clear. I have assigned both to you.

**Comment by kelson42** [comment]
@amire80 Your expertise might be helpful here. It seems the Unicode Consortium [libicu](https://github.com/unicode-org/icu) does not properly support Ladakhi (see this ticket and #611). We don't really use the latest version, but I suspect this is the same with the cutting edge version. Would you be able to confirm this and inform us why? Would that make sense to make a bug report upstream? If "yes", how?
