### ISSUE TITLE
No JS fallback for kiwix-serve welcome page

### ISSUE THREAD

**Issue by rgaudin** [kiwix/libkiwix#615]
The new kiwix-serve UI is more practical but it's now impossible to use kiwix-serve without JS enabled.

There are many ways to solve this but if we consider no-js to be an edge case, we could, at least have a `<noscript />` tag pointing to a separate endpoint with a static list of contents.

<img width="1009" alt="Screen Shot 2021-09-13 at 10 25 23" src="https://user-images.githubusercontent.com/57929/133068218-06397efc-9562-438d-97af-7244484c2baf.png">

**Comment by thavelick** [comment]
@kelson42 - I'd be happy to work on this if there's need and no one else is tackling it. I've been considering updating kiwix-serve to do something like this regardless.

**Comment by kelson42** [comment]
@thavelick Yes, you are welcome to work on this ticket.

**Comment by mgautierfr** [comment]
>  we could, at least have a \<noscript /> tag pointing to a separate endpoint with a static list of contents.

We don't have this static list now (except raw xml catalog opds feed)

---

Somehow related to #716, if we don't have js support, we probably want to have this list to point to the "nojs viewer" (raw content) of the zim.
Don't know where/when to handle this, but to keep in mind.

**Comment by kelson42** [comment]
@thavelick Any news?

**Comment by kelson42** [comment]
I guess, @thavelick has abandonned the idea to propose an alternative here. We ahould really define what we want to build exactly.

**Comment by mgautierfr** [comment]
> We don't have this static list now (except raw xml catalog opds feed)
> Don't know where/when to handle this, but to keep in mind.

I now have something in mind 🙂 

The current frontpage is a js page which does specific request to opds catalog, parse the xml result and render the what is parsed dynamically.
We could simply render the catalog "odps" feed with hmtl. 
The opds catalog is rendered to xml using (`OpdsDumper`)[https://github.com/kiwix/libkiwix/blob/master/src/opds_dumper.cpp].
which is using mustache templates to generate xml.
If we use different templates, we should be able to generate html/css content without too much trouble on our side.
User would simply directly browse the (user friendly view of the) catalog.

We may loose some features (as the list of categories) but it should mostly works.

---

- Categories are accessible throw a specific request to the opds catalog. We could also render in html those list to allow user to browse only a category
- html template could have `<form>` to allow user to do a search on catalog

**Comment by veloman-yunkan** [comment]
> We could simply render the catalog "odps" feed with hmtl.

@mgautierfr If I read that sentence literally, I think that hardly there is anyone who can do it at all :wink:

**Comment by kelson42** [comment]
I'm not sure where everywhere there is javascript. But could we maybe first implement #750 in C++ (instead of the js we have currently) first? This would be better from a UX as well.

**Comment by juuz0** [comment]
Following mgautierfr's words above, I was able to get the same design of tiles without JS (injecting details using mustache in html file):
![image](https://user-images.githubusercontent.com/26814569/218342948-d12d1acb-3b50-430a-9c55-f4ed86d44e55.png)

Haven't looked into how language/category filtering concretely for this. But maybe a `<a>` link for every language/category filtered catalog? Needs discussion here

Current draft: #897

**Comment by kelson42** [comment]
Bravo @juuz0 !
