### ISSUE TITLE
Prepare release 10.0.0

### ISSUE THREAD

**Issue by kelson42** [kiwix/libkiwix#618]

**Comment by hashworks** [comment]
Hi! Any timetable for this? I'm currently providing both libzim v7 for zim-tools v3 and libzim v6 for libkiwix v9, it would be great if I could resolve that soon with libkiwix v10 :)

**Comment by kelson42** [comment]
@hashworks I guess this will take a few additional weeks, we have a handfull of tickets left in the milestone. We are eager as well to do the release because we have been working since a year on libkiwix10.0.0.

**Comment by kelson42** [comment]
Will be released next week
