### ISSUE TITLE
Function `kiwix::fileExists` does not behave properly if file exists but is not readable

### ISSUE THREAD

**Issue by kelson42** [kiwix/libkiwix#619]
During the review of https://github.com/kiwix/kiwix-tools/pull/477, I discovered a wrong behaviour:
```
$ ls -la index.html 
-rwx------ 1 root root 2649 Okt 11 15:14 index.html
$ kiwix-serve --port=8081 --customIndex=index.html  phzh_core-greek-one_el_2020-12.zim 
ERROR: No such file exist /home/kelson/code/kiwix-tools/index.html
```

The problem is that `kiwix::fileExists` returns `false`... and actually it should return `true`.

I see two solutions to that problem:
* `kiwix::fileExists` is renamed to `kiwix::fileExistsAndReadable`
* An additional function `kiwix::fileReadable` is created.

... and then all usages of this code should be checked to see if the test is appropriate.

We should also consider to have this/these method(s) generating the error message so it can be reused... but now sure how to do that properly.

**Comment by karandeeppotato** [comment]
@kelson42 
Sir, I am stuck at this for so long.
Whenever I execute 
`kiwix-serve --port=8081 --customIndex=index.html sample_zim.zim
`

Instead of getting this error,
`ERROR: No such file exist /home/kelson/code/kiwix-tools/index.html`

I am getting this,
`kiwix-serve: unrecognized option '--customIndex=index.html'`

Am I doing something wrong here?

**Comment by kelson42** [comment]
@karandeeppotato Probably because you don't launch your local compiled version of kiwix-serve, but the one of the system. Try:
```
$./kiwix-serve --port=8081 --customIndex=index.html sample_zim.zim 
```

**Comment by karandeeppotato** [comment]
@kelson42 
I didn't find any function by the name `kiwix::fileReadable` and `kiwix::fileExistsAndReadable`

But I do notice this behavior that when I execute this command 
`kiwix-serve --port=8081 --customIndex=index.html sample_zim.zim 
`
It is perfectly working.

But when I execute this command from the home directory like you did.

> $ ls -la index.html 
-rwx------ 1 root root 2649 Okt 11 15:14 index.html
$ kiwix-serve --port=8081 --customIndex=index.html  phzh_core-greek-one_el_2020-12.zim 
ERROR: No such file exist /home/kelson/code/kiwix-tools/index.html

Then I am getting this error.
`ERROR: No such file exist (or file is not readable)/home/geekpotato/index.html`

**Comment by mgautierfr** [comment]
That is the point :
`kiwix::fileExists` check that the file is readable (and so, implicitly, that it exists). But the behavior of the function must correspond to its name.

On the same time, the global behavior we want on kiwix-serve is to check that the file is readable (so the behavior you see for kiwix-serve is correct).

So we must correctly fix the behavior of `fileExists` but keep the "is readable" check on kiwix-serve.

Introducing a `kiwix::fileReadable` or `kiwix::fileExistsAndReadable` is a way to fix this dilemma.

**Comment by juuz0** [comment]
I'm getting 
`ERROR: No such file exist (or file is not readable)/home/juuzou/.local/share/kiwix/index.html`
Seems to be fixed?

**Comment by kelson42** [comment]
@juuz0 Can you please just rename the function to `kiwix::fileExistsAndReadable`? Adding a space character after the parenthesis seems necessary as well.
