### ISSUE TITLE
Front page must be prepared for zim file with missing metadata

### ISSUE THREAD

**Issue by mgautierfr** [kiwix/libkiwix#624]
Pretty old zim file may have no favicon at all.
In this case, the opds stream doesn't contain any node for the favicon.
(The node `<link rel="http://opds-spec.org/image/thumbnail" [...]/>`)
Opds stream is :
```
<feed xmlns="http://www.w3.org/2005/Atom" xmlns:opds="http://opds-spec.org/2010/catalog">
  <id>f2f68963-ed3a-f761-c43a-c94cdfaae6c2</id>
  <title>Filtered zims (count=17.515151515151516&amp;start=0)</title>
  <updated>2021-10-21T14:34:07Z</updated>
  <totalResults>1</totalResults>
  <startIndex>0</startIndex>
  <itemsPerPage>1</itemsPerPage>
  <link rel="self" href="" type="application/atom+xml" />
  <link rel="search" type="application/opensearchdescription+xml" href="/catalog/searchdescription.xml" />
  <entry>
    <id>urn:uuid:9bcd90f8-db78-5d68-1a81-2528ca25e806</id>
    <title>wikipedia en wp1-0.7 2009-05</title>
    <updated>T00:00:00Z</updated>
    <summary></summary>
    <language></language>
    <name></name>
    <flavour></flavour>
    <category></category>
    <tags>_ftindex:no;_pictures:yes;_videos:yes;_details:yes</tags>
    <articleCount>90284</articleCount>
    <mediaCount>0</mediaCount>
    
    <link type="text/html" href="/wikipedia_en_wp1-0.7_2009-05" />
    <author>
      <name></name>
    </author>
    <publisher>
      <name></name>
    </publisher>
    
  </entry>
</feed>
```

For now, the front page's js ends with a "undefined" url for the favicon and set the html image src to undefined. And so the browser do a request with "undefined" query.
Front page should not set a icon at all if there is none in the opds stream.

**Comment by kelson42** [comment]
@MananJethwani In case there is no illustration in the OPDS feed, would you be able please to just display nothing?

**Comment by mgautierfr** [comment]
There is also the same problem with the lang.

Here what is look like (with ui from PR #628)
![Capture d’écran du 2021-11-03 10-24-32](https://user-images.githubusercontent.com/86161/140037058-2d420176-fac7-4dc9-9923-644a177329d5.png)

**Comment by juuz0** [comment]
Is this still up? 
I would like try it
Also, if you could link a zim to test this issue

**Comment by kelson42** [comment]
This is still up, but I don't know exactly the whole scope of the ticket.

**Comment by mgautierfr** [comment]
> Also, if you could link a zim to test this issue

The issue I've got is with a pretty old zim file. It is not available anymore. I can upload it somewhere but you don't need a zim file.
If you use kiwix-serve with a library, kiwix-serve will trust the library and don't load metadata from the zim file.
You can simply remove metadata from the xml and see how it behaves.
(kiwix-serve will check however that the zim actually exists at the path specified in the library)

**Comment by juuz0** [comment]
Thanks, I can reproduce the language issue but not the favicon one (even if I remove the favicon url from library).
In the ideal case, that white box should be removed for no language right?

**Comment by kelson42** [comment]
> In the ideal case, that white box should be removed for no language right?

I gess so, i would just make a css display:none in that case.

**Comment by juuz0** [comment]
Making css `display:none` will push the book tags (the ones at bottom right) to left side, `background-color: transparent` looks much better choice

**Comment by kelson42** [comment]
Display:hidden ?

**Comment by juuz0** [comment]
That works also, and sounds more logical
