### ISSUE TITLE
Kiwix-serve topbar inputs should have titles

### ISSUE THREAD

**Issue by kelson42** [kiwix/libkiwix#647]
See here:
![image](https://user-images.githubusercontent.com/1029718/145371837-e5ac8bd1-9011-4f82-b30c-7853a9977251.png)

* The homepage button should have "Got to welcome page"
* The ZIM homepage button should be "Go to the main page of '<title>'"
* The Randompage button should be: "Go to a randomly selected page"
* The Search input shoudl be:  "Search '<title>'"

**Comment by VaibhavPaliwal0007** [comment]
@kelson42 I would like to work on this issue. Can you guide me on how to get started?

**Comment by mgautierfr** [comment]
What is the rational for this change ?

I'm not against that but it would be better to know (or explicit) why we do it.
The current situation comes from this https://github.com/kiwix/kiwix-tools/pull/200 where we removed the text and use icons instead.
It would be nice to have the motivation, at least for historical reason when we will come back on this in 4 years :)

**Comment by kelson42** [comment]
@mgautierfr This is an accessibility problem

**Comment by kelson42** [comment]
After reading https://stackoverflow.com/questions/27953425/what-is-the-difference-between-aria-label-and-title-attributes it seems we should actually have "title" and "aria-lable" attributes. The first for the visual tooltip and the second for the screen readers.

**Comment by mgautierfr** [comment]
> This is an accessibility problem

Ok. I was thinking you wanted to revert the change and put textual information instead of the icons.
