### ISSUE TITLE
Update Kiwix-serve cache strategy

### ISSUE THREAD

**Issue by kelson42** [kiwix/libkiwix#650]
Kiwix serve delivers many types of content:
1.  ZIM content
2. Kiwix-serve static content
3. Kiwix-serve dynamic content (API, search, etc.)

For each type, here is how we want to cache:
1. ZIM content: cache as long as the (concerned) content does not change
2. Kiwix-serve static content: cache as long as we don't run a different version of kiwix-serve
3. Kiwix-serve dynamic content: cache as long as the (concerned) library has not been updated

Which implies 3 different strategies...

## ZIM content

ZIM content does give us no freedom about the URLs calls and we have no way to garanty that what is available at the URL at two different times is the same content. Therefore the content can be cached but must be revalidate (with `Etag` issued from the ZIM ID). To avoid a systematic revalidation we can set a max-age of one hour like `Cache-Control: max-age=3600, must-revalidate`.

## Kiwix-serve static content

This is the easier case, we need to "cache busting", for example by adding `?UNIQUE_ID` at the end of the URL of any of the resources. This `UNIQUE_ID` should be fixed at compilation time. `Cache-Control: max-age=31536000, immutable` then should be enough (so no other related HTTP headers, like  `Etag`, `Last-Modified` or `Expires`).

## Kiwix-serve dynamic content

The dynamic content is consistent and can be cached as long as the library is not updated or the server restarted. I would propose to force systematically revalidation with an `Etag` which is changed each time the internal library is changed. The cache policy would look like `Cache-Control: max-age=0, must-revalidate`.

**Comment by kelson42** [comment]
@veloman-yunkan I want to make a new attempt to sortout this problem of cache. Because the problem is broader than the API or Etag, I have close #598, but thank you very much again for your explanation which are perfectly correct I think now. Would you be able please to assess this ticket and tell me if you disagree with something? Or maybe you would have an other approach to do it better?

**Comment by kelson42** [comment]
While you are waiting and interacting with @mgautierfr on https://github.com/kiwix/libkiwix/pull/679 and I suspect it might take weeks ; I would really appreciate to have you looking at this ticket.

**Comment by veloman-yunkan** [comment]
> While you are waiting and interacting with @mgautierfr on #679 and I suspect it might take weeks ; I would really appreciate to have you looking at this ticket.

@kelson42 OK, will do.

**Comment by veloman-yunkan** [comment]
> == Kiwix-serve static content ==
> 
> This is the easier case, we need to "cache busting", for example by adding `?UNIQUE_ID` at the end of the URL of any of the resources. This `UNIQUE_ID` should be fixed at compilation time. `Cache-Control: max-age=31536000, immutable` then should be enough (so no other related HTTP headers, like `Etag`, `Last-Modified` or `Expires`).

This presents some maintenance challenge. kiwix-serve static resources are referenced in other static resources. For example, `static/templates/index.html` references, among others, `static/skin/isotope.pkgd.min.js`, `static/skin/iso6391To3.js`, `static/skin/index.js`:

https://github.com/kiwix/libkiwix/blob/ce24b1fa5f4ab2d128329b233d50c474cee1d3c0/static/templates/index.html#L41-L43

By adopting this scheme, whenever we update a static resource and change its unique id, we must make sure that all relative URLs pointing to that resource are updated too. Without automated frontend testing we will need to be careful in order to prevent mismatches between the resource ids and the cross references in sibling resources.

I will try to figure out how to circumvent this difficulty.

**Comment by kelson42** [comment]
> By adopting this scheme, whenever we update a static resource and change its unique id, we must make sure that all relative URLs pointing to that resource are updated too. Without automated frontend testing we will need to be careful in order to prevent mismatches between the resource ids and the cross references in sibling resources.

From this comment, I'm not 100% sure we have a common understanding about how to do this "cache busting". Whatever the value of `?UNIQUE_ID` (in the `script` nodes URLs for example), kiwix-serve will deliver the proper content as the js resource name stays sthe same (everything before the question mark). The only point is that if the browser cache will handle things properly.

From the technical side the should probably be a random string given by Meson to the compiler (like the version number) and it should be then set as template value and replaced accordingly.

**Comment by veloman-yunkan** [comment]
@kelson42 I never said that the solution won't work. My point was that a straightforward implementation will add some maintenance headache. For example, `static/templates/index.html` contains the following line:

```
<script type="text/javascript" src="{{root}}/skin/index.js" defer></script>
```

We can change it to

```
<script type="text/javascript" src="{{root}}/skin/index.js?v1" defer></script>
```

and then, when we modify `static/skin/index.js`, change it again to 

```
<script type="text/javascript" src="{{root}}/skin/index.js?v2" defer></script>
```

and so on. I am looking for an approach that will work automatically.

P.S. I reread my previous comment and found the sentence which suggested that I doubted the viability of the proposed solution. I wrote

> Without automated frontend testing we will need to be careful in order to prevent mismatches between the resource ids and the cross references in sibling resources.

Indeed, if in the server we simply ignore the `?UNIQUE_ID` token, then nothing will work worse compared to what we have now (but forgetting to update the `?UNIQUE_ID` component for a modified resource will still lead to the issue nicely [summarized](https://github.com/kiwix/kiwix-tools/issues/505#issuecomment-992331870) by @mgautierfr).

**Comment by veloman-yunkan** [comment]
> I am looking for an approach that will work automatically.

What about the following scheme?

The quasi-revision¹ of a resource can be obtained automatically by the following command:

```
git log --oneline static/skin/STATIC_RESOURCE_PATH|wc -l
```

When new commits affecting `static/skin/STATIC_RESOURCE_PATH` are added this number only grows and can serve as a base for deriving the `UNIQUE_ID` token for that resource.

We can have a script that preprocesses the templates in `static/templates/` by appending thus obtained `?UNIQUE_ID` suffixes to URLs starting with `{{root}}/skin/`. 

---

**Comment by kelson42** [comment]
> When new commits affecting `static/skin/STATIC_RESOURCE_PATH` are added this number only grows and can serve as a base for deriving the `UNIQUE_ID` token for that resource.

OK
 
> We can have a script that preprocesses the templates in `static/templates/` by appending thus obtained `?UNIQUE_ID` suffixes to URLs starting with `{{root}}/skin/`.

I think it is better to to that in meson and C++. Your approach seems less clean and robust to me... but you are the dev. and as long as it works and @mgautierfr agree with it, this is fine to me.

**Comment by veloman-yunkan** [comment]
> The quasi-revision¹ of a resource can be obtained automatically by the following command:
> 
> ```
> git log --oneline static/skin/STATIC_RESOURCE_PATH|wc -l
> ```
> 
> When new commits affecting `static/skin/STATIC_RESOURCE_PATH` are added this number only grows and can serve as a base for deriving the `UNIQUE_ID` token for that resource.
> 
> We can have a script that preprocesses the templates in `static/templates/` by appending thus obtained `?UNIQUE_ID` suffixes to URLs starting with `{{root}}/skin/`.

Relying on `git` for obtaining the `UNIQUE_ID` of a resource will create obstacles when building libkiwix from downloaded (rather than cloned) source. A workaround is to add to the repository a file with revisions of all static resources and update it in an automatic way using the above method.

**Comment by veloman-yunkan** [comment]
> == ZIM content ==
> 
> ZIM content does give us no freedom about the URLs calls and we have no way to garanty that what is available at the URL at two different times is the same content. Therefore the content can be cached but must be revalidate (with `Etag` issued from the ZIM ID). To avoid a systematic revalidation we can set a max-age of one hour like `Cache-Control: max-age=3600, must-revalidate`.

How should this interact with the decoration of `text/html` content? If `Etag` is issued from the ZIM ID only, then a change in the taskbar templates will not invalidate the cache and we may arrive at a situation where out-dated taskbar code will work in combination with updated front-end code served via the `/skin` endpoint. Even simpler, restarting the server with a different value for the `--urlRootLocation` option will break the taskbar because of the cached responses with the old value of `{{root}}` in

https://github.com/kiwix/libkiwix/blob/5c38300504b96eb37dc69b92152970afd3d97fde/static/templates/taskbar_part.html#L5-L20

**Comment by veloman-yunkan** [comment]
This may be a good time to once again reconsider #394

**Comment by kelson42** [comment]
@veloman-yunkan Your two last comments are pertinent IMO. In this ticket I simply have chosen to ignore the fact that part (taskbar) of each article is chrome and is conceptually different... and that treating it in an undifferentiated manner would lead to unexpected behaviours. This is just a limitation of the current design IMO.

See my comment at https://github.com/kiwix/libkiwix/issues/394#issuecomment-1029116285. #394 is part of the current milestone `10.1.0` and could be implemented ASAP. Considering that @mgautierfr will be pretty busy in the next weeks with many tickets related to compilation/CI/CD, you are currently in first row to run this effort. This makes even more sense if you feel impaired by #394 for this ticket. So, if you want, go for it.

**Comment by rgaudin** [comment]
Stepping into the discussion as we are revamping library.kiwix.org's frontend (reverse proxy). As discussed with @kelson42, we'd want kiwix-serve to respond properly and not hack its responses into the proxy.

From what I understand, here's to do:

- #394 must be implemented ; with an iframe pointing to `/raw`.
- A unique *library hash* must be set/computed on each library refresh. Could be a UUID (assuming every restart/reload is library change) or a digest of the book IDs (**better** caching but more costly to generate).
- `/catalog/` and `/search|suggest/` requests for multi-ZIM to be ETag'd with the library hash ID plus no-cache.
- `/catalog/` and `/search|suggest/` requests for single-ZIM (`v2/illustration` for instance) to be ETag'd with the BookID plus a long max-age.
- `/raw/` responses to be ETag'd with the BookID plus a long max-age.
- `/skin|external/` can follow two paths:
  - each resource is hashed and linked-to using the query-param trick. Ensures resources that have not been updated across versions are kept in cache but setup/maintenance is important. Either no ETag or reuse of the cache with long cache.
  - responses to be ETag'd with the kiwix-serve/libkiwix version plus long cache. Good start and very easy to implement IMO. Could be a first step.
- `/` (homepage) to be ETag'd with kiwix-serve/libkiwix version and long cache as well.
-  content pages (have we settled on changing the API and only serve from `/content/`?) would be ETag'd with the library ID plus no-cache.

⚠️ **Important notes**
- `--urlRootLocation` is not to be worried about. Priority goes to end users. Switching locations is not our problem
- `--nodatealias` will not be the hell it could have been thanks to #394. Pages under a no-date-alias or not would both include an iframe to the period-including URL under `/raw/`.

**Comment by kelson42** [comment]
@rgaudin Thx, it clarifies the behaviour with non-static content and seems correct me. Hopefuly for @veloman-yunkan and @mgautierfr as well?

**Comment by kelson42** [comment]
@veloman-yunkan Now, that the fix to have an iframe based taskbar runs the last revirw ozeration, could we go fotward with this ticket?

**Comment by veloman-yunkan** [comment]
> @veloman-yunkan Now, that the fix to have an iframe based taskbar runs the last revirw ozeration, could we go fotward with this ticket?

@kelson42 Yrs, qe cuolf :smile:

**Comment by kelson42** [comment]
@veloman-yunkan Looks like we are now back to this ticket. Do you need to split it in smaller pieces?

**Comment by veloman-yunkan** [comment]
@kelson42 I am starting to work on it and will file subtickets as needed.
