### ISSUE TITLE
Add frontend version in the frontend resource urls.

### ISSUE THREAD

**Issue by mgautierfr** [kiwix/libkiwix#656]
The frontend resources (js/css/html) are cached by the browser.
If we change the frontend, users may not use the last version as the browser will never ask for it, even if kiwix-serve has been updated.

If we change the resource url to include the frontend version, the browser will "detect" the change and then will ask for the new frontend version.

_Originally posted by @mgautierfr in https://github.com/kiwix/kiwix-tools/issues/505#issuecomment-992331870_

**Comment by kelson42** [comment]
@mgautierfr It seems we agree on this :) see the ticket i have open a few days ago https://github.com/kiwix/libkiwix/issues/650

**Comment by mgautierfr** [comment]
Indeed. I'm closing this issue as duplicated.
