### ISSUE TITLE
Should invalid ZIM be loaded?

### ISSUE THREAD

**Issue by rgaudin** [kiwix/libkiwix#657]
Wasted some time trying to understand why my kiwix-serve homepage was broken. It was due to a ZIM in my library not having the [mandatory `Language` metadata](https://wiki.openzim.org/wiki/Metadata): JS code assumes a language code and crashes if it's missing.

As this metadata (and a few others) are mandatory, shouldn't libkiwix/kiwix-serve refuse to load them with an explicit message instead of accepting whatever is in the library?

**Comment by kelson42** [comment]
Similar to #624

**Comment by mgautierfr** [comment]
I think it would be a pity to not use a somehow valid content because the Language/Illustration/... entry is missing. We are using content that come from different creators (and times) and we should be prepared for missing content.

**Comment by rgaudin** [comment]
> I think it would be a pity to not use a somehow valid content because the Language/Illustration/... entry is missing. We are using content that come from different creators (and times) and we should be prepared for missing content.

Agrees with the beginning of what you say but not the ending. If we consider that allowing different creators means they won't be able or want to respect the spec, then we should remove those requirements from the spec.

If we are talking about legacy ZIM, then, yes, I also think we should be flexible ; partly because we have a co-responsability in this as we didn't enforce the spec earlier.
But being flexible is costly and requires additional handling otherwise you end up with the current behavior: to please ZIM makers, we are breaking the experience for ZIM users (exaggerating 🙃).

I suggest we run a script over all ZIMs in our library to find out which of those mandatory stuff are missing and in which porportion. This way, we can limit out flexible handling to those needed.

A warning in kiwix-manage could be useful I think.

**Comment by mgautierfr** [comment]
> If we consider that allowing different creators means they won't be able or want to respect the spec, then we should remove those requirements from the spec.

It is not because something is MUST in a spec that reader MUST discard content not following the spec.
There is a lot of way a zim files may not follow the spec. Having our readers crashing on wrong zim files is not a good idea. And "it is not following the spec" is not a valid reason to don't care.

I don't say we must try to read everything.
I just want us to decide if we discard such zim file on the consideration of benefice (reading more zim) vs inconvenient (more complex implementation).

> If we are talking about legacy ZIM, then, yes, I also think we should be flexible

How do you differentiate legacy ZIM files from ZIM files created with wrong metadata ?

> to please ZIM makers, we are breaking the experience for ZIM users

It is matter of point of view. If a user have contents from a maker not following the specs, and that content always worked in the past. The user will now have useless zim files (even if they were).
We are breaking user's experience, not maker one 🙃 

> I suggest we run a script over all ZIMs in our library to find out which of those mandatory stuff are missing and in which porportion.

It is a good idea, at least to have some stats to base on our decision.
But we have to remember that there is a lot of zim files in nature (the one I used in #624 is one of them).

> A warning in kiwix-manage could be useful I think.

Definitively. It may even be here that we discard the zim files.

**Comment by rgaudin** [comment]
I believe we agree on what's important:

- we don't want to prevent users from reading their ZIM files
- we want to balance our development/maintenance efforts

Fortunately, we've got a few things to help

**we write the spec** so we can reconsider part of it. You seem to genuinely believe that part of it won't be respected so maybe we should ask ourselves why and consider a different wording. *required* != *recommended* for instance.
Except for validators, spec implementation always are within a strict-flexible spectrum. That's normal.
We'd benefit from being clear about our objectives (and making sure the spec respects our format vision).

**we create 99+% of all ZIM files** and we can update most of them so it's relatively easy to go from a situation with say 30% of ZIMs respecting the spec to 98%. Random numbers obviously.

**we'll fix metadata in the CMS** so even ZIMs that can't be updated will be able to have fixed metadata in the near future.

**we already have flexible readers**. Current stable versions are quite permissive so the remaining (probably rare but impossible to account for) use cases are not left without a solution. They would still be able to use the current version.

I am **not in favor of being strict** but it's clear from the many important changes going on that we're at a point where it's pertinent to ask ourselves whether we want to keep being flexible (ie. devel time) or if we use this opportunity to be more strict.

If we get to settle this, some tickets triaging/resolution will be easier.

**Comment by juuz0** [comment]
Would like to mention here that Kiwix-desktop doesn't load a zim if language metadata is missing

**Comment by kelson42** [comment]
@juuz0 interesting, sounds alonost like a bug to me.

**Comment by kelson42** [comment]
> Would like to mention here that Kiwix-desktop doesn't show a zim in the libary if language metadata is missing

I have open https://github.com/kiwix/kiwix-desktop/issues/754

**Comment by kelson42** [comment]
> As this metadata (and a few others) are mandatory, shouldn't libkiwix/kiwix-serve refuse to load them with an explicit message instead of accepting whatever is in the library?

I'm, in the principle, pretty against this approach, but if handling a missing metadata I would be able to consider to do it. So it depends.

> I suggest we run a script over all ZIMs in our library to find out which of those mandatory stuff are missing and in which porportion. This way, we can limit out flexible handling to those needed.

Definitly, I count with the CMS to help to identify the ZIM which have not been "renewed" or "updated" to secure an overall quality.

@rgaudin Not sure there is really much more we can do with this ticket.
