### ISSUE TITLE
[kiwix-serve] filters do not work

### ISSUE THREAD

**Issue by juuz0** [kiwix/libkiwix#660]
Choosing `English` shows me no results
The url also doesnt seem to be correct?

https://user-images.githubusercontent.com/26814569/146645525-31ee6810-cdec-4f58-bc3d-f6d819b721ff.mp4

**Comment by kelson42** [comment]
@juuz0 strange... Any chance you can investigate?

**Comment by juuz0** [comment]
@kelson42 Oops x3
Strange and funny it works fine on all URLs except 127.0.0.1

**Comment by kelson42** [comment]
@juuz0 It should work exactly the same whatever the url? Which request exactly gives different results? Please call the API.

**Comment by juuz0** [comment]
@kelson42 There's some inconsistency here. 
* The video in the main comment is of Firefox - that doesn't display filtered contents properly for any address - as seen from the video, it populates the URL with `http://192.168.18.8:8080/?lang=bis%22%3EBislama%3C%2Foption%3E%3Coption+value%3D`
* I tried with a second browser (Vivaldi, Chromium based) - that displays filtered contents properly for all addresses except 127.0.0.1.

Steps I've followed:
1. Run kiwix-serve with `kiwix-serve --library ~/.local/share/kiwix/library.xml --port=8080` 
2. choose English from "All languages"

**Comment by kelson42** [comment]
@juuz0 It's a display issue or an api issue? we need to have a clear reproduction case.

**Comment by juuz0** [comment]
@kelson42 I'm inclined to it being an API issue with parsing the file language.
Looking into the HTML,
`<option value="asm&quot;>অসমীয়া</option><option value=" eng"="">English</option>` This ruins all options I think, too much junk in those values

For reproduction, maybe these can help (a libary.xml and 3 zims):
https://drive.google.com/drive/folders/1MTQkyo_th5isu_2n0qWXymKpzYeuWHju?usp=sharing

**Comment by kelson42** [comment]
@juuz0 Wuld you be able to simplify the bug with only one zim file?

**Comment by juuz0** [comment]
I think there's a need of atleast 2 zim files (different languages) to reproduce this

**Comment by kelson42** [comment]
Which files exactly, so I can reproduce the problem?

**Comment by kelson42** [comment]
Will check, thx for the details.

**Comment by juuz0** [comment]
This fixes all of the problems *except* the error remains only for the address `127.0.0.1` 
Though I wouldn't re-open it for that, feel free to do so
