### ISSUE TITLE
Don't introduce taskbar for non-front articles

### ISSUE THREAD

**Issue by rgaudin** [kiwix/libkiwix#671]
When creating a ZIM, HTML Items with `FRONT_ARTICLE=false` hints are considered non-front articles. As such, the taskbar should not be introduced for them.

I'm not sure about how it should be implemented as Hints are create-time only. I suppose it would rely on the index…

This should allow us to stop depending on `text/html;raw=true` mime types.

**Comment by kelson42** [comment]
Related to #394
