### ISSUE TITLE
Add title with full language name behind kiwix-serve language badge.

### ISSUE THREAD

**Issue by kelson42** [kiwix/libkiwix#692]
We display "EN", and we should add a title "English" and we should do so everywhere (for all language badges).

First reported in 2017 at https://github.com/kiwix/web/issues/24

**Comment by juuz0** [comment]
What does behind mean here? Is this about replacing EN by English, like this:
![image](https://user-images.githubusercontent.com/26814569/151554326-bdaadca7-56bb-4c8c-9d59-c4c7b857ba71.png)
![image](https://user-images.githubusercontent.com/26814569/151554380-fbd75c5e-e753-44c6-b20d-1f3f9bbe8523.png)

**Comment by kelson42** [comment]
@juuz0 This is not what I meant. I mean adding HTML attributes like following: `title="English" aria-label="English"` to get a tooltip.

**Comment by juuz0** [comment]
Thanks, would like to do this!
