### ISSUE TITLE
Deb CI failing: Unsupported release hirsute

### ISSUE THREAD

**Issue by kelson42** [kiwix/libkiwix#695]
See recent action https://github.com/kiwix/libkiwix/runs/4971228815?check_suite_focus=true.

The error is recurring and not sporadic.

**Comment by kelson42** [comment]
@legoktm I suspect that this CI shoukd be removed because Hirsute is EOL, see https://www.mail-archive.com/kernel-packages@lists.launchpad.net/msg470392.html

**Comment by legoktm** [comment]
I submitted PRs for all the repos.

**Comment by kelson42** [comment]
Fixed by #698
