### ISSUE TITLE
root.xml has summary in place of description

### ISSUE THREAD

**Issue by tim-moody** [kiwix/libkiwix#707]
https://wiki.openzim.org/wiki/Metadata has a mandatory Description, but https://library.kiwix.org/catalog/root.xml has instead a `<summary>`

**Comment by kelson42** [comment]
What should be the proper behaviour to your opinion?

**Comment by mgautierfr** [comment]
From the OPDS spec (https://specs.opds.io/opds-1.2#513-summary-and-content) I understand that summary should be used for a small text describing the content and to be display to the user.
From this part (https://specs.opds.io/opds-1.2#511-relationship-between-atom-and-dublin-core-metadata) I understand that we should use `atom:summary` and not `dc:description`.
