### ISSUE TITLE
Introduce ZIM file size in OPDS entry

### ISSUE THREAD

**Issue by tim-moody** [kiwix/libkiwix#708]
Size is in the href for the image, but I don't see it for the zim itself. This is important for checking storage when automating downloads.

**Comment by tim-moody** [comment]
Actually It is in root.xml and the Kiwix server, but not in the opds feed returned by iiab.me. Is that due to the version of kiwix-serve?

https://library.kiwix.org/catalog/search?name=wikipedia_en_all
http://iiab.me/kiwix/catalog/search?name=wikipedia_en_all

my kiwix-serve version is

root@iiab-me:~# /opt/iiab/kiwix/bin/kiwix-serve -V
kiwix-tools 3.2.0

libkiwix 10.0.1
+ libzim 7.2.0
+ libxapian 1.4.18
+ libcurl 7.67.0
+ libmicrohttpd 0.9.72
+ libz 1.2.8
+ libicu 58.2.0
+ libpugixml 0.12.0

libzim 7.2.0
+ libzstd 1.5.1
+ liblzma 5.2.4
+ libxapian 1.4.18
+ libicu 58.2.0

**Comment by kelson42** [comment]
@tim-moody Indeed! Pretty surprised it is not there. This is important to have it and to be able to filter based on it.

See https://www.dublincore.org/specifications/dublin-core/dcmi-terms/terms/extent/

**Comment by veloman-yunkan** [comment]
> Actually It is in root.xml and the Kiwix server, but not in the opds feed returned by iiab.me. Is that due to the version of kiwix-serve?

@tim-moody OPDS feed contains the `<link rel="http://opds-spec.org/acquisition/open-access" type="application/x-zim" href="{{{url}}}" length="{{{size}}}" />` element only for those entries that have a download link associated with them (in library.xml it is defined via the `url` attribute).

**Comment by kelson42** [comment]
@veloman-yunkan I don't understand. If you look at view-source:https://library.kiwix.org/catalog/search?name=wikipedia_en_all, there is nothing like this `<link rel="http://opds-spec.org/acquisition/open-access" type="application/x-zim" href="{{{url}}}" length="{{{size}}}" />`, but all the ZIM files are downloadable!

**Comment by kelson42** [comment]
@tim-moody So actually all good, no reason to keep this ticket open right?

**Comment by tim-moody** [comment]
So to summarize:

* in the old library_zim.xml zim size was an explicit attribute
* in the new root.xml it is an attribute of a link attribute
* in library.kiwix.org/catalog that link is present along with the size attribute
* in a locally installed kiwix-serve the opds feed does not include the link attribute because it is thought not to be downloadable and therefore it also does not include the size attribute

Is that correct?

**Comment by veloman-yunkan** [comment]
Yes

**Comment by veloman-yunkan** [comment]
> * in a locally installed kiwix-serve the opds feed does not include the link attribute because it is thought not to be downloadable and therefore it also does not include the size attribute

Though this is slightly an overstatement (a wrong generalization of your current setup). A locally installed kiwix-serve can perfectly serve downloadable files. It all depends on the contents of the libary.xml file it was started with.

**Comment by tim-moody** [comment]
>Though this is slightly an overstatement (a wrong generalization of your current setup). A locally installed kiwix-serve can perfectly serve downloadable files. It all depends on the contents of the libary.xml file it was started with.

so you are saying there are some conditions in which the link would be present in the opds feed from a locally installed kiwix-serve? what are they?

**Comment by tim-moody** [comment]
The library.xml file on iiab.me was created entirely with kiwix-manage. It includes a relative path from the location of library.xml, but no url.

**Comment by tim-moody** [comment]
To return to the original topic, I think the situation has been clarified with respect to when and where a size attribute is present.

In my view having an explicit size attribute is a better design than having it inside of a link. @kelson42 if you disagree then it makes sense to close this ticket.

**Comment by veloman-yunkan** [comment]
> The library.xml file on iiab.me was created entirely with kiwix-manage. It includes a relative path from the location of library.xml, but no url.

You can edit the library.xml file and add a `url` attribute for those ZIM files that can be downloaded from somewhere (for ZIM files created by you, you will have to put them online or in your LAN - kiwix-serve doesn't serve ZIM files).

**Comment by kelson42** [comment]
I thin, situation is pretty clear now. Sorry I was not able to identify first the length attribute. Problem solved.

**Comment by mgautierfr** [comment]
kiwix-serve does two different things:
- Serve the content in zim archives. To do so, it needs zim files accessible in a file system.
- Expose a list of zim archives in a catalog. To do so, it doesn't need zim file accessible[*]. A library.xml properly filled up is enough.

But kiwix-serve doesn't allow to download a zim file itself. You need a (static) file server somewhere.
If you want kiwix-serve to put a download link in the catalog (and so, a size), you must give the download url to kiwix-serve, as it can't know it. So you need to set a `url` in the library.xml

----

[*] Saying that, the catalog (`root.xml`, `search`, `v2`, ...) always returns books with local and valid zim files. And there is no way for now to have the list of remote books (ones with download link/url) whatever if they are local or not. It would be pretty easy to change (technically) but it add some functional complexity (API to define, kiwix-serve frontend assuming catalog returns books readable by kiwix-serve, ....)

**Comment by tim-moody** [comment]
@mgautierfr yes, I am only interested in local zims. The use case is for someone who is not internet connected and has the Kiwix android app to be able to get the url for downloading a local zim in the OPDS feed. As you say, the actual download would be served by the web server not kiwix-serve. (Internet in a Box has functionality to permit side loading the android app from the server.)

We currently just use what kiwix-manage produces to populate library.xml. Are you saying we could by whatever means add a url attribute and kiwix-serve will include that in the opds feed?

The url in library_zim.xml is an attribute like url="https://download.kiwix.org/zim/ted/ted_en_playlist-open-source-open-world_2021-12.zim.meta4"

The library.xml produced by kiwix-manage has a similar format and I only need to add a space delimited string like that in library_zim.xml to have it included in the output. Size is already there.

**Comment by kelson42** [comment]
```
$ kiwix-manage --help
kiwix-manage: unrecognized option '--help'
Usage:
	kiwix-manage LIBRARY_PATH add ZIM_PATH [OPTIONS]
	kiwix-manage LIBRARY_PATH remove ZIM_ID [ZIM_ID]...
	kiwix-manage LIBRARY_PATH show [ZIM_ID]...

Purpose:
	Manipulates the Kiwix library XML file

Arguments:
	LIBRARY_PATH	is the XML library file path.

	ACTION		is the pre-defined string to specify the action to run on the XML library file.

			Must be one of the following values:
			* add: add a ZIM file to the library
			* remove: remove a ZIM file from the library
			* show: show the content of the library

	ZIM_ID		ZIM file unique ID

	OPTIONS		Custom options for "add" action:
			--zimPathToSave=CUSTOM_ZIM_PATH to replace the current ZIM file path
			--url=HTTP_ZIM_URL to create an "url" attribute for the online version of the ZIM file

			Other options:
			-v, --version to print the software version

Examples:
	Add ZIM files to library: kiwix-manage my_library.xml add first.zim second.zim
	Remove ZIM files from library: kiwix-manage my_library.xml remove e5c2c003-b49e-2756-5176-5d9c86393dd9
	Show all library ZIM files: kiwix-manage my_library.xml show

Documentation:
	Source code	https://github.com/kiwix/kiwix-tools
	More info	https://wiki.kiwix.org/wiki/Kiwix-manage

```

**Comment by tim-moody** [comment]
even better. didn't realize url was an OPTION
