### ISSUE TITLE
Wrong html entities in kiwix-serve ft result page

### ISSUE THREAD

**Issue by kelson42** [kiwix/libkiwix#723]
Look:
![image](https://user-images.githubusercontent.com/1029718/157459589-86e3e236-ddb1-4444-a997-867ef120ff54.png)

Which should properly see the search pattern with "<toto>"

**Comment by juuz0** [comment]
Assigning back to mgautierfr - fixed already, I assume

**Comment by kelson42** [comment]
@juuz0 Why you believe it is fixed? I have obviously tested with latest master head.

**Comment by juuz0** [comment]
@kelson42 I meant with https://github.com/kiwix/libkiwix/commit/a83e99dcee3823de32ecf6e435f287a9a3dc3997 in PR https://github.com/kiwix/libkiwix/pull/724

**Comment by kelson42** [comment]
OK, should be tested, but woukd be surpised.

**Comment by juuz0** [comment]
I did test, shows
![image](https://user-images.githubusercontent.com/26814569/157912923-63414dff-db75-4cc6-951d-7f22ccc9a7da.png)

**Comment by kelson42** [comment]
WONDERFUL!
