### ISSUE TITLE
Use fake language in our translation unit tests.

### ISSUE THREAD

**Issue by mgautierfr** [kiwix/libkiwix#749]
Following #679

The current tests on translation are based on Armenian language. But it is subject to translation made on translatewiki.
We should use a fake language we could use on test to be sure that translator will not break our tests.

**Comment by kelson42** [comment]
Translatewiki uses « qqq » for comments abour strings. Maybe you can reuse that code?

**Comment by veloman-yunkan** [comment]
qqq.json contains only descriptions of messages without placeholders for parameters that must be replaced in the real message. Thus using qqq pseudolanguage in the unit tests will not verify that parameters are properly set in the code.

**Comment by kelson42** [comment]
`000` ?

**Comment by mgautierfr** [comment]
Or `test` ?

**Comment by kelson42** [comment]
@mgautierfr @veloman-yunkan Can we go forward with `test`

**Comment by kelson42** [comment]
@mgautierfr @veloman-yunkan please use artificial `test` Language for testing

**Comment by kelson42** [comment]
@veloman-yunkan Woukd be good if that one could be implemented. Seems straight forward.
