### ISSUE TITLE
Correctly parse `Accept-Language` header.

### ISSUE THREAD

**Issue by mgautierfr** [kiwix/libkiwix#750]
The PR #679 add a preliminary support for `Accept-Language` header. It assumes the header contains a single language.
But most browser fill the header with a list of weighted accepted language. See commit message of 927c125

We should correctly parse the header.

**Comment by kelson42** [comment]
@veloman-yunkan It’s not thenright moment to fix/implement this ticket? I guess you need that for #846 as well.
