### ISSUE TITLE
[URGENT] Use gzip instead of deflate

### ISSUE THREAD

**Issue by rgaudin** [kiwix/libkiwix#753]
The server currently supports Content-Encoding for the `deflate` flavor only.

There are 3 flavors in the wild:

- `deflate` which uses the DEFLATE algorithm. It used to have a lot of issues in browser implementations in the past but that's all forgotten with modern browsers I believe. It's slightly faster than gzip (simpler digest).
- `gzip` which uses the DEFLATE algorithm also but its format is different (headers and CRC). Most supported everywhere in browsers but also in reverse proxies.
- `br` Brotli. Most recent and fastest I believe but support is missing in some browser and only through modules in reverse proxies.

Has we use kiwix-serve extensively behind a reverse proxy, it would greatly help and simplify deployments if it supports gzip as gzip is the lingua-franca for compression in reverse-proxies (nginx, varnish).

[this post](https://stackoverflow.com/questions/1838699/how-can-i-decompress-a-gzip-stream-with-zlib) and [zlib](https://zlib.net/manual.html#Gzip) describes the differences and indicates switching should be fairly simple.

I'm in favor of simply replacing deflate by gzip for maintenance's sake. I am unaware of any use case of deflate-only support in a client.

**Comment by kelson42** [comment]
FYI @rgaudin is working on revamping the https://library.kiwix.org infrastructure (see https://github.com/orgs/kiwix/projects/14) to allow quicker/smaller HTTP responses and a robuster setup of the Service. He relies on the implementation of this feature (and a new release of libkiwix and build of kiwix-serve) to complete his work *next week*. @veloman-yunkan @mgautierfr Not sure who is in best position to do this, but this would be really great to put what you are doing on stall and implement this (should be relatively quick anyay) so we can deliver the new https://library.kiwix.org infrastructure end of next week.
