### ISSUE TITLE
Why use human ID in OPDS illustration endpoint?

### ISSUE THREAD

**Issue by rgaudin** [kiwix/libkiwix#755]
Illustration URLs from the OPDS are of the following format

```
/catalog/v2/illustration/ted_en_playlist-open-source-open-world_2021-12/?size=48
```

What is the reasoning behind using the *dated-human ID* instead of the Book ID in this endpoint?

**Comment by mgautierfr** [comment]
We simply didn't think about this. Indeed the bookId should be better as it is not a url written by human.

**Comment by kelson42** [comment]
@veloman-yunkan Considering that this change will break the API, that there is a consensus on it, that we are not to far to release `12.0.0` and that this change seems pretty trivial. Would that be possible to do it now?
