### ISSUE TITLE
[REGRESSION] Suggestions are not diacritics insensitive anymore

### ISSUE THREAD

**Issue by DerK777** [kiwix/libkiwix#758]
Hello. I Have some problems with kiwix. Software version 2.2.1 Windows Desktop Russian. File Wikipedia russian 04.2022. But all older versions had the same problems. Please help to find a solution.
1. When I write in the search line, for example, "Тайфун" (Typhoon), it didn't find it. It offers "полнотекстовый поиск" (full-text search) and then I get link to "Тайфун (значения)" (Typhoon (meanings)), and only then I can get to article "Тайфун" (Typhoon).
![Снимок1](https://user-images.githubusercontent.com/13303079/164884353-f65feefb-11de-4add-a05c-726198b17406.PNG)
![Снимок2](https://user-images.githubusercontent.com/13303079/164884383-882def87-39b3-456b-a386-25a9f7a2861d.PNG)
But it works really good with the word "Ураган" (Hurricane), for example.
![Снимок3](https://user-images.githubusercontent.com/13303079/164884470-77277fe2-35c4-478c-a60d-bf29cba89a7e.PNG)
2. Search didn't work at all if I try to do it at second and other tabs. There is no any links, there is no "полнотекстовый поиск" (full-text search), nothing
![Снимок4](https://user-images.githubusercontent.com/13303079/164884557-61a20372-e067-4b54-bd7d-598c80687039.PNG)
It didn't depend on language, it didn't find "Hurricane" too.
![Снимок5](https://user-images.githubusercontent.com/13303079/164884642-4ec72945-ae8b-4b6e-9a57-616b847a4312.PNG)

**Comment by veloman-yunkan** [comment]
> This is a major regression AND I wonder how this can go through the unit test without been noticed!

@kelson42 We don't have such a unit-test for suggestions that checks handling of diacritics. Also, while trying to add one (as the first step toward resolving this issue), I ran against the problem that the ZIM files used in our libkiwix unit tests don't have any articles with diacritics in the titles.

**Comment by kelson42** [comment]
@veloman-yunkan If is it necessary to implement #601 fo get this feature properly tested then we will have to do that in TOP priority IMO. But, at the level of maturity we have now in libkiwix, such a regression is for me a bad surprise. Correlated to #722 and #742, this let me think a strong and quick push in searching features automated testing is necessary.
