### ISSUE TITLE
Round count in homepage request

### ISSUE THREAD

**Issue by rgaudin** [kiwix/libkiwix#766]
kiwix-serve homepage builds a dynamic catalog request based on viewport size which results in requests like:

```
http://library.kiwix.org/catalog/search?start=0&count=12.591946308724832
```

kiwix-serve understandably returns 12 entries for such a request. I believe the JS code should round this number so that:
- we make clean-looking requests that look like we know what we're doing
- we benefit from our varnish cache frontend instead of serving all those *unique* requests from kiwix-serve.

**Comment by kelson42** [comment]
@juuz0 Would you be able please to quicklly fix this?

**Comment by juuz0** [comment]
@kelson42 👍
