### ISSUE TITLE
Magnet link makes no sense

### ISSUE THREAD

**Issue by rgaudin** [kiwix/libkiwix#767]
kiwix-serve, when offering ZIM file downloads offers both a torrent file and a *magnet file*.

`magnet:` is an URL scheme that is understood by browsers and torrent applications but it is not a file type. The magnet link should have the content of that file as its `href` value. Should this be too complicated to implement, I believe (but that's just my personal opinion) that the magnet link should be removed altogether.

Serving a text file with a long link as content looks broken and decreases the overall impression of the tool.

**Comment by kelson42** [comment]
@juuz0 Doable at the time the download widget is loaded to read the magnet link page and fill the « href » attribute?
