### ISSUE TITLE
Error uploading ubuntu package in CI

### ISSUE THREAD

**Issue by mgautierfr** [kiwix/libkiwix#798]
It seems that uploading package in the CI fails because of a invalid secret key see:
https://github.com/kiwix/libkiwix/runs/7406215507?check_suite_focus=true

@legoktm, do you know what happens here ?

**Comment by kelson42** [comment]
Seems to work again, see https://github.com/kiwix/libkiwix/runs/7436274197?check_suite_focus=true

**Comment by juuz0** [comment]
Though not exactly error due to uploading, but impish is failing here also
https://github.com/kiwix/libkiwix/runs/7478840879?check_suite_focus=true

**Comment by legoktm** [comment]
Sorry, I'm at a conference this weekend. I'll try to look today but definitely will by Monday.
