### ISSUE TITLE
[REGRESSION] Kiwix-serve suggestions somehow broken

### ISSUE THREAD

**Issue by kelson42** [kiwix/libkiwix#811]
With latest libzim/libkiwix/kiwix-tools, the kiwix-serve suggestion does not work anymore. I just need to start the kiwix-serve to get this
![image](https://user-images.githubusercontent.com/1029718/188304693-28f18871-5078-44b9-aea3-d6f9f41c508a.png)

The problem is that the content is not transmited properly, see `content=content` in the URL. This is clearly a regression.

It seems that under certain conditions the suggestions work again, but I have not been able to identify how exactly.

**Comment by kelson42** [comment]
@juuz0 Could you please urgently have a look, I suspect this is somehow a bug which has been introduced at the time jquery has been removed.

**Comment by kelson42** [comment]
Acutally it seem:
* totally broken if article is displayed
* fully working if fulltext search result is displayed

**Comment by juuz0** [comment]
checking it.
Although I don't get suggestions either at https://library.kiwix.org/wikipedia_en_all_nopic_2022-01/A/User:The_other_Kiwix_guy/Landing (this is the jquery version of suggestions)

**Comment by kelson42** [comment]
@juuz0 Can you please give a feedback here? This is the only blocker left for 12.0.0 milestone and this regression has probably been introduce during the removal pf jquery.

**Comment by juuz0** [comment]
@kelson42 I finally got some, working on this now. Though, maybe I need a brief on new changes in this regard:
![image](https://user-images.githubusercontent.com/26814569/191964965-077338c1-a4ba-43fa-9f32-dc395b3bedb6.png)


which is the correct taskbar (and how do I disable the old one)

**Comment by kelson42** [comment]
@juuz0 Browser cache problem? We have now the top bar within an iframe!

**Comment by juuz0** [comment]
@kelson42 this seems to be fixed in latest master? (probably after addition of `viewer.js`)

**Comment by kelson42** [comment]
@juuz0 Lucky guy ;) I will check.

**Comment by kelson42** [comment]
@juuz0 I confirm that it seems to work now. I guess we have to thank @veloman-yunkan
