### ISSUE TITLE
`autoComplete.min.js` is already minified in the code repository

### ISSUE THREAD

**Issue by kelson42** [kiwix/libkiwix#819]
I wonder if this is already minified:
* Why this is minified (is that really necessary)?
* How to read it?
* How to modify it?

Usually, the way of doing is to have a "working" version not minified and then minify the file at release (or even runtime). Why we don't do so?

**Comment by veloman-yunkan** [comment]
@kelson42 That file was imported by #796 from [another project](https://github.com/TarekRaafat/autoComplete.js). We are not supposed to edit it.

IMO, the real problem is that there is no reference to the origin of that file. I had it in mind during review but somehow forgot to mention.

**Comment by kelson42** [comment]
@veloman-yunkan I understand now. Doing so has obviously many problems or things to verify:
* verify if we comply and how to comply with original license
* we should better not integrate this in our code base. We should better handle it like an external dependence
* check if it coukd be packaged by Debian

**Comment by veloman-yunkan** [comment]
Adding @mgautierfr since he was the one to add `autoComplete.min.js` in #639

**Comment by legoktm** [comment]
Just like the other JavaScript that was previously in the repo, it's fine to have but we should include a non-minified version that mentions the license. I'll submit a PR for that shortly.
