### ISSUE TITLE
Auto-hiding of the taskbar in the iframe-based viewer

### ISSUE THREAD

**Issue by veloman-yunkan** [kiwix/libkiwix#820]
Introduction of iframe-based viewer (#716) broke the auto-hiding functionality of the taskbar. Auto hiding (enabled for narrow-screens) works correctly only for the first page loaded in the viewer. Navigating to other pages interferes with auto-hiding as follows:

- If the toolbar was hidden, it stays hidden.

- If the toolbar was not hidden, it loses the ability to auto-hide.

**Comment by kelson42** [comment]
We should fix that, not having a top ar is a serious regression IMO.
