### ISSUE TITLE
OPDS catalog must respect the used nameMapper

### ISSUE THREAD

**Issue by MohitMaliFtechiz** [kiwix/libkiwix#828]
**Describe the bug**
On libkiwix 10.1.1 , zim file while opening over hotspot resulting ```The requested URL "/" was not found on this server.```.

**Expected behavior**
Its should open the zim file without any issue

**Screenshots**
![Screenshot from 2022-10-03 18-52-57](https://user-images.githubusercontent.com/34593983/193588946-e4684153-6689-46ec-9f8b-7cfa55dc1bae.png)
![Screenshot from 2022-10-03 18-53-01](https://user-images.githubusercontent.com/34593983/193588952-83e8bc93-4e7d-446c-ace0-b7e469981f57.png)

**Environment**
- Version of Kiwix Android : 3.7.0
- Device : REDMI NOTE 9
- OS version : 11

**Comment by kelson42** [comment]
@mgautierfr @veloman-yunkan Sounds like a regression to me. Isn't it?

**Comment by mgautierfr** [comment]
> However, the opds_stream always uses the "humanReadableIdFromPath". It is the bug (to fix) and it always have been this way.
The "regression" comes from the switch from backend generated home page to dynamic js home page which use the catalog as source.

This is not a regression from the opds_stream point of view as the bug was always here.
This is a regression from the homepage point of view and it dates from libkiwix 10.0.0 (but the bug is on opds_stream side)

**Comment by kelson42** [comment]
@mgautierfr Thx for clarification. IMO, we better get it fixed befpre 12.0.0 release.

**Comment by veloman-yunkan** [comment]
I will work on this.

**Comment by mgautierfr** [comment]
I'm working on this

**Comment by veloman-yunkan** [comment]
I've started with some clean-up of OPDS dumper. I've now shared my work as a self contained PR #829.

**Comment by veloman-yunkan** [comment]
I guess that #829 in its current form can be merged first without causing too much pain for #830. I won't continue working on it.
