### ISSUE TITLE
Add a feed link to kiwix-serve welcome page

### ISSUE THREAD

**Issue by kelson42** [kiwix/libkiwix#832]
The feed link should have the same filter (URL) as the one currently running.

Read https://medium.com/samsung-internet-dev/add-rss-feeds-to-your-website-to-keep-your-core-readers-engaged-3179dca9c91e form more details.

This should help user to be kept informed about new release of their most wanted ZIM files.

**Comment by s-pratik** [comment]
Hi, I would like to contribute I am very new in this can anyone help me with how can I start

**Comment by mgautierfr** [comment]
The opds stream is itself a atom feed (as opds is based on atom). It should not be to complicated to "add" a feed, we should have only to add some declaration to "itself" in the opds stream (if not already done)

**Comment by kelson42** [comment]
Here the ticket is about adding the OPDS link in the kiwix-serve HTML "welcome" page.

**Comment by mgautierfr** [comment]
The source of the welcome page is a opds feed, so a atom feed. We just have to properly link to this feed from the welcome page.

**Comment by juuz0** [comment]
The blog says there are 2 ways of advertising:

> 1. Firstly for helping users see that there is an RSS feed available you should display the RSS feed icon on your website and have it link to the feed version of the current page.

 > 2. The other main method of advertising your RSS feed is by a machine readable HTML tag in the head of the HTML page. This isn’t visible to users but will inform the user’s Web browser and RSS client that there is an RSS version of that site.
 
 Which one is preferred here?

**Comment by kelson42** [comment]
@juuz0 This ticket does request to advertise it. Although this might be a good idea, I have no opinion on this. Good browser (extensions) just display a feed icon in the URL bar if a feed is available in the HTML head node. This is only what is requested here.

**Comment by Popolechien** [comment]
I don't think we should assume users to be tech-savvy and install extensions by default. I would support discrete advertising.

**Comment by kelson42** [comment]
> I don't think we should assume users to be tech-savvy and install extensions by default. I would support discrete advertising.

Yes, just try the approach "one problem at a time".

**Comment by kelson42** [comment]
> 1. Firstly for helping users see that there is an RSS feed available you should display the RSS feed icon on your website and have it link to the feed version of the current page.

Now, that the feed is make available in the HTML head, lets talk about that. Maybe putting this small icon just beside the "Powered by Kiwix" would be a good approach?

**Comment by juuz0** [comment]
A small icon beside "Powered by Kiwix" would look fine, though I think there's a small accessibility problem there.
If there are a large number of ZIMs, "powered by Kiwix" would be far too down in the page (For example, at library.kiwix.org - we have to scroll through thousands of ZIMs to see the text).

Alternatively, the logo can be right-aligned to the page - in the same line as Filters.
![Untitled design](https://user-images.githubusercontent.com/26814569/216824283-5491190e-582d-446e-a2b5-8b27eaf84ff8.png)
![Untitled design(1)](https://user-images.githubusercontent.com/26814569/216824293-24632f1f-2443-4763-9317-2e190c0023b6.png)
![Untitled design(2)](https://user-images.githubusercontent.com/26814569/216824302-e5085ff0-4186-42a1-b266-946cc7241113.png)


*Although the designs were well thought out, at this moment juuz0 realised why Art wasn't his strongest subject at school...*

**Comment by kelson42** [comment]
@juuz0 You are right, the second design/screenshot looks good IMO

**Comment by juuz0** [comment]
@kelson42 should i make modifications to the current PR then? or create a new issue -> new PR to link

**Comment by kelson42** [comment]
@juuz0 Yes, it's OK

**Comment by Popolechien** [comment]
This top section. And by _frozen_ I refer to excel or google sheets, where you can block the top row on top and scrolling down only moves the rows below
![Capture d’écran 2023-02-06 à 10 31 48](https://user-images.githubusercontent.com/21675885/216936066-b16a19c8-54d6-4dd4-b93a-d49320fae994.png)

**Comment by kelson42** [comment]
@Popolechien Indeed! It's not frozen and this is strange. We should tacle this in an other ticket.
