### ISSUE TITLE
How to handle bookmarks

### ISSUE THREAD

**Issue by kelson42** [kiwix/libkiwix#840]
Each Kiwix reader handles bookmarks on its own although this is always the same:
* Add
* Get
* Remove
* Export
* Import

I wonder if this would be a smart idea to propose the primitive in the libkiwix?

**Comment by mgautierfr** [comment]
This is already the case.
Search for bookmark in [library.h](https://github.com/kiwix/libkiwix/blob/master/include/library.h)

**Comment by kelson42** [comment]
@mgautierfr Really good, do we have a storage backend in it? An xml/json file for bookmarks (something like for the local library)?

**Comment by mgautierfr** [comment]
Yes, kiwix-desktop should write a xml file along with your library.xml file.
Something like `~/.local/share/kiwix/library/library.bookmarks.xml` (or another path if you are on Windows or using flatpak)

**Comment by kelson42** [comment]
@mgautierfr Actually all this is for kiwix-android. Wonder how much we could/should share with other readers like kiwix-desktop. Wouldn't be good to have the reader/writer within libkiwix?

**Comment by mgautierfr** [comment]
Saving the bookmarks is made with [`kiwix::Library::writeBookmarksToFile`](https://github.com/kiwix/libkiwix/blob/master/include/library.h#L254) and reading a bookmark file is done with [`kiwix::Manager::readBookmarkFile`](https://github.com/kiwix/libkiwix/blob/master/include/manager.h#L118-L124). This follow the same convention than for writing/reading `library.xml`.

Other projects just have to use the methods.
