### ISSUE TITLE
Multiple .so file on linux tar file on nightly

### ISSUE THREAD

**Issue by MohitMaliFtechiz** [kiwix/libkiwix#853]
We have found two .so file on nightly upload for linux architecture on https://download.kiwix.org/nightly/libkiwix_linux-x86_64.tar.gz. Shared library was showing as 0mb while other with release number were working.

Same issue with libzim also 

![Screenshot from 2022-12-06 17-30-59](https://user-images.githubusercontent.com/34593983/205906743-09ca6156-3241-473f-940a-8ffd0cd17af1.png)

**Comment by kelson42** [comment]
This is not a bug, the two 0B files are symbolic links.
