### ISSUE TITLE
kiwix-serve should compress web fonts

### ISSUE THREAD

**Issue by kelson42** [kiwix/libkiwix#854]
After releasing libkiwix `12.0.0` and kiwix-serve `3.4.0`, this has been deployed on https://library.kiwix.org, and I have renewed a performance test of the welcome page. Overall results looks good, but there is improvement potential.

One of them is around resources size/load times:
![image](https://user-images.githubusercontent.com/1029718/206169187-b2bf4a6e-4b01-4c26-9c9d-90dee433c5ce.png)

You can see that we have `318KB` of Web-font loading at first load (I understand the Web-font should be cached properly) which is pretty heavy and I think we could/should improve the situation here without much hassle.

It looks like actually the Web-fonts are not gzip compressed, look:
```bash
$ curl --compressed -I "http://192.168.178.24:8181/skin/fonts/Roboto.ttf?cacheid=84d10248"
HTTP/1.1 200 OK
Connection: Keep-Alive
Content-Length: 168260
Content-Type: application/font-ttf
Access-Control-Allow-Origin: *
Cache-Control: max-age=31536000, immutable
Date: Wed, 07 Dec 2022 11:33:09 GMT

```

I made a small test with `gzip` on the command line and we could get both of them for only `159KB`. We should have this for our skin Web-fonts, but would be great also to do the same on ZIM based Web-fonts.

Therefore I would recommend to compress the Web-fonts (all kind of them). It seems actually that compressing the Web-fonts is recognized like a good practice, see for example:
https://www.fastly.com/blog/new-gzip-settings-and-deciding-what-compress#new-gzip-settings

**Comment by rgaudin** [comment]
@kelson42 am I expected to do something specific here? Like compress skin fonts on the reverse-proxy ?

**Comment by kelson42** [comment]
@rgaudin This is a request for libkiwix/kiwix-serve... and in a first place a question. So I first ask if you agree this would be an improvement. But if this is super easy to do in Varnish, you can consider it. That would allow to have an immediate improvement, instead of waiting next release... If this ticket is good idea at all!

**Comment by rgaudin** [comment]
OK ; I don't have a strong opinion on this ATM.

To be honest, I think we should have a holistic approach about optimizing kiwix-serve responses: do we need both fonts ? why ? can we defer some? do we need a distinct endpoint for viewer js ? Can't we load languages list on first click? etc.

These tools brings a lot of insight with a lot of improvement potential but I'm afraid looking at just a few independently might be less efficient than sitting down a couple hours and laying out a plan.

I am especially suggesting this in the light of the coming hackathon which would have us four together.

---

Because it's not mentioned in the post, those results are from https://gtmetrix.com/

**Comment by kelson42** [comment]
@rgaudin What you suggest is the good idea and I have put it in the agenda. That said, this question/ticket can also be considered independently IMO. It's either an improvement or not, and this independently of any other consideration.

**Comment by mgautierfr** [comment]
I think than even more than compressing the resource when we send it. We could also compress it when we create/store it in the binary. It would use less space in the binary and we would have to simple send it without compressing it at runtime.

**Comment by mgautierfr** [comment]
Adding the font mimetypes in https://github.com/kiwix/libkiwix/blob/master/src/server/response.cpp#L61-L68 should do the job
