### ISSUE TITLE
Handle "multiple language" special language

### ISSUE THREAD

**Issue by kelson42** [kiwix/libkiwix#872]
We have a special code `mul` as language code in a zim. It should be possible to handle ir and make selections based on it. It seems this is not fully implemented, at least this is not visible in language select box on kiwix server.

**Comment by rgaudin** [comment]
`mul` itself is implemented in that it is mapped to `Multiple Languages` (unlike other non-ISO-codes) string and available in the selector. See #841

<img width="812" alt="Screenshot 2023-01-27 at 12 22 29" src="https://user-images.githubusercontent.com/57929/215086028-3cb5c4f0-88e4-451b-8b92-53fc13c38f25.png">

That said, there aren't many `mul` ZIMs in our catalog and it may be time to question it's usefulness. Not to remove the feature but to set better metadata on those ZIMs if appropriate.

I don't know much about phet but gutenberg should be fixed to list the correct languages.

I believe libkiwix is already handling multiple languages (multiple, comma-separated ISO-639-3 codes in `Language`)

**Comment by kelson42** [comment]
@rgaudin Your feedback seems really pertinent to me. I think that at that point we could/should replace `mul` by a specific list of language everywhere and deprecate this `mul` special language in Kiwix.

@rgaudin @veloman-yunkan @mgautierfr Would a agree with that plan?

**Comment by rgaudin** [comment]
Not sure what the plan is but yes, I think we should update the ZIM metadata instead. Users won't be looking for “multiple language ZIMs”, makes no sense ; they will be looking for their language of choice and the resulting ZIMs might be multiple-languages (in which case the lang codes should be shown) or not.

**Comment by mgautierfr** [comment]
Mostly agree with the plan. `mul` doesn't contain any useful information and so is useless. Better use a list of languages.
But we have to be sure libkiwix handle that correctly before removing `mul` in favor of this list.

**Comment by rgaudin** [comment]
@mgautierfr I just tested and indeed it's not supported

<img width="520" alt="Screenshot 2023-02-22 at 09 50 22" src="https://user-images.githubusercontent.com/57929/220584428-a74a34f8-6767-4770-baaa-7b69ce9befe9.png">

**Comment by rgaudin** [comment]
Should any of you need it for testing ; here's the [test-mul.zim](http://tmp.kiwix.org/test-mul.zim)

**Comment by kelson42** [comment]
We should:
* identofy the list of zim with mul to modify recipes and or scrapers
* fix the support of multiple languages in libkiwix.

**Comment by kelson42** [comment]
We have now tickets for all the points which have to be fixed. Closing this one.
