### ISSUE TITLE
Make aria2 wrapper and Downloader thread safe/compliant.

### ISSUE THREAD

**Issue by mgautierfr** [kiwix/libkiwix#873]
See https://github.com/kiwix/kiwix-desktop/issues/87#issuecomment-1403594478

aria2 wrapper use a lock to prevent concurrent access to the curl handle. This create a bottleneck as we can do only one request at the time. If one request takes time (and starting a download does on window) all other requests are delayed (and blocked).

We should make aria2 wrapper thread compliant and also make `Downloader` thread safe to allow a real multi thread usage of `Downloader`

(Not sure we need to make `Download` threadsafe. We can simple state that methods on one `Download` are not threadsafe)

**Comment by kelson42** [comment]
Seems pretty urgent if we want that https://github.com/kiwix/kiwix-desktop/issues/87 works fine.
