### ISSUE TITLE
For Android, can we compile libkiwix with external dat file?

### ISSUE THREAD

**Issue by kelson42** [kiwix/libkiwix#874]
See https://github.com/kiwix/kiwix-android/issues/9

**Comment by kelson42** [comment]
@mgautierfr Has implemented this for Android. You confirm?

**Comment by mgautierfr** [comment]
This is already done.
See directory `/share/icu/73.2/` in https://download.kiwix.org/nightly/2023-11-17/libkiwix_android-arm64-2023-11-17.tar.gz
