### ISSUE TITLE
Normalize Language Codes?

### ISSUE THREAD

**Issue by rgaudin** [kiwix/libkiwix#875]
Currently, there is is one ZIM with an incorrect ISO-639-3 `Language` code in the library.

It is using `Fra` (see ([coopmaths](https://library.kiwix.org/raw/coopmaths_2023-01/meta/Language)) instead of `fra` which is the valid one.

Obviously the ZIM needs to be fixed (I just fixed the recipe). @RavanJAltaie please check all your recipes for Title-cased language codes and fix them.

Now libkiwix normalizes the `lang` query string so that it can take any case and the lookup is done on the lowercase version.

This means that both the filter (`fra`, `français`) and (`Fra`, `Fra`) return the same results. In the reader and in the catalog.

```sh
❯ curl -s 'https://library.kiwix.org/catalog/v2/entries?lang=fra&count=1'|grep totalResults
  <totalResults>240</totalResults>

❯ curl -s 'https://library.kiwix.org/catalog/v2/entries?lang=Fra&count=1'|grep totalResults
  <totalResults>240</totalResults>
```

**Question**: should the kiwix-serve reader consider this a *supported* (frequent enough) scenario and normalize all non-valid ISO-639-3 to lowercase (and retry matching) or should it stay as it is because it's ZIM-creator responsibility and can be fixed in `library.xml` anyway.

**Comment by kelson42** [comment]
I’m not in favour of implementing this loosy casing support. Once we do that here we will have to handle this variant (which is not ISO compliant AFAIK) everywhere. Lots of unecessary hassle IMO.

**Comment by rgaudin** [comment]
Great; now this will disappear once the incorrect recipies are all fixed, redone and new ZIM enter the library.

I wonder if we should prevent creating zim with non iso Language code in scraperlib. Non ISO are used for mul and for not yet standardized languages.

**Comment by kelson42** [comment]
> I wonder if we should prevent creating zim with non iso Language code in scraperlib. Non ISO are used for mul and for not yet standardized languages.

Yes, we should prevent to create this kind of wrong metadata.
