### ISSUE TITLE
Serbo-croate language does not appear properly in kiwix-serve language selection box

### ISSUE THREAD

**Issue by kelson42** [kiwix/libkiwix#889]
This is what we have currently:
![image](https://user-images.githubusercontent.com/1029718/217590133-b5359933-3010-46bf-8392-813a04758bbc.png)

In place of `hbs` we should read something like srpskohrvatski (https://en.wikipedia.org/wiki/Serbo-Croatian)

**Comment by juuz0** [comment]
Ez fix #891
