### ISSUE TITLE
Add a "pointer" cursor and tool-tip on UI language selector.

### ISSUE THREAD

**Issue by mgautierfr** [kiwix/libkiwix#900]
Small suggestion (from @juuz0)
Maybe the UI language selector icon could have cursor as "pointer" & a tool-tip to tell what it does

_Originally posted by @juuz0 in https://github.com/kiwix/libkiwix/issues/846#issuecomment-1438697702_

**Comment by mgautierfr** [comment]
Answer from @veloman-yunkan 

>  Small suggestion: Maybe the UI language selector icon could have cursor as "pointer" & a tool-tip to tell what it does

The tricky question regarding the tooltip for the change-UI-language button - what language should it be in? In the current language of always in English?

Also, I figured out that the header text of the UI language selector is not translated, so the same (above) question applies to it too.

**Comment by juuz0** [comment]
> The tricky question regarding the tooltip for the change-UI-language button - what language should it be in? In the current language of always in English?

Going by how it's done in almost every app, the tooltip & header text should be in current language imo

**Comment by veloman-yunkan** [comment]
> > The tricky question regarding the tooltip for the change-UI-language button - what language should it be in? In the current language of always in English?
> 
> Going by how it's done in almost every app, the tooltip & header text should be in current language imo

The hint for this particular action is special and has to be in a language that has the highest chance of being understood by the user. I believe that at this instant in the history of humankind that language is English.
