### ISSUE TITLE
[SERVER][UI] Correctly display multi languages in the home page

### ISSUE THREAD

**Issue by mgautierfr** [kiwix/libkiwix#908]
Here is a screen shot of how it is display now :

![image](https://user-images.githubusercontent.com/86161/223769562-215201a9-f0a7-41e3-b3f1-4e083a2fce68.png)

How we should display it is still a open question

**Comment by veloman-yunkan** [comment]
I think that for a book with the number of languages exceeding some reasonable limit (say, 3), the language label should read "*N* languages" with the list of languages shown separately on hover. Clicking such a label should not trigger filtering by language.

**Comment by juuz0** [comment]
The language label could also expand its width, to show all languages assocted, on hover/click itself.

P.S.: I can't reproduce this, all Multiple language ZIMs show "MUL" as language for me. Is this a different setting to be enabled?

**Comment by kelson42** [comment]
> P.S.: I can't reproduce this, all Multiple language ZIMs show "MUL" as language for me. Is this a different setting to be enabled?

@juuz0 No, you can see it at https://dev.library.kiwix.org/#lang=eng&q=&category=phet

**Comment by kelson42** [comment]
> I think that for a book with the number of languages exceeding some reasonable limit (say, 3), the language label should read "_N_ languages" with the list of languages shown separately on hover. Clicking such a label should not trigger filtering by language.

Agree with this proposition modulo we display "MUL" if multiple languages, that way we have always onely "one language" displayed language and this is coherent.

So we "just" need to extend the current tooltip which display the full name of the language, to a tooltip which display the list of full nameds languages.

**Comment by juuz0** [comment]
> You have worked the most around this. Does that make sense? Would you be able to implement this?

Yeah, certainly. I'll get on this

> No, you can see it at https://dev.library.kiwix.org/#lang=eng&q=&category=phet

I can see this yes but I can't download those files (Not found URL when downloading). Do you have a working link where I can download.

I downloaded 2 old MUL files from download.kiwix.org (2023-01 and 2022-12) but they show up like this in current kiwix-serve:
![image](https://user-images.githubusercontent.com/26814569/232323058-7d55da2f-83ff-4810-9b8d-fb97cda7d180.png)

**Comment by kelson42** [comment]
@juuz0 Thank you! Here it is https://mirror.download.kiwix.org/zim/.hidden/dev/phet_mul_all_2023-04.zim
