### ISSUE TITLE
No cursor on UI language switch button?

### ISSUE THREAD

**Issue by rgaudin** [kiwix/libkiwix#913]
Is there a reason for not having a cursor indicating interactivity on the UI language switch button? Or is it just missing?

![Screen_Shot_2023-03-15_at_11_34_29](https://user-images.githubusercontent.com/57929/225297401-d7b59c2b-a7b9-47b2-bd1a-5c8c56253b1a.png)

**Comment by kelson42** [comment]
@veloman-yunkan Not one of the small UI things you want to fix?

**Comment by rgaudin** [comment]
Maybe a duplicate of #900 but the feed one has the pointer…

**Comment by veloman-yunkan** [comment]
This ticket is duplicate of #900 which was closed by #910
