### ISSUE TITLE
Look-and-feel mismatch between the kiwix-serve welcome page and the viewer

### ISSUE THREAD

**Issue by veloman-yunkan** [kiwix/libkiwix#917]
> > In welcome page, font shows correctly 
> > But it doesn't while browsing a book
> 
> This is a manifestation of a more general discrepancy in the look-and-feel of the welcome page and the viewer page. I think we better address it separately.

Please don't forget to create the ticket then.

_Originally posted by @kelson42 in https://github.com/kiwix/libkiwix/issues/910#issuecomment-1468379699_

**Comment by kelson42** [comment]
What are the rationals behind this buggy behaviour?

**Comment by veloman-yunkan** [comment]
@kelson42 I don't think that there are any rationals. Simply no one paid attention to it.

**Comment by veloman-yunkan** [comment]
@kelson42 And I also want to note that the new viewer reproduced the look-and-feel of the old viewer (which by that time was already different from the welcome page).

**Comment by kelson42** [comment]
@veloman-yunkan In case there is a doubt, this good to go/fix on my side. We should fix before `12.1.0` release.

**Comment by kelson42** [comment]
@veloman-yunkan Any chance you could quickly fix this in the near future?

**Comment by veloman-yunkan** [comment]
@kelson42 I will try

**Comment by kelson42** [comment]
Mostly fixed with #1009
