### ISSUE TITLE
Kiwix Design Revamp - Homepage

### ISSUE THREAD

**Issue by ghost** [kiwix/libkiwix#921]
Description -
Here is the Figma URL: https://www.figma.com/file/atKBgNfsDz5MvmsOGHY2ls/kiwix?node-id=126-244&t=E2Opi57AQX4IqwRa-0. You should be referring to "For Developers" tab from the left hand navigation.

Meta Data Description to be considered during the development of page as below (this is only a recommendation, but if you have any alternative data then feel free to use them.)
- Title: Kiwix - Free and open-source software that brings knowledge to millions
- Description: Kiwix is a free and open-source software that allows you to access knowledge offline without internet connection. Download Kiwix Desktop or Kiwix for Mobile today.
- Keywords: kiwix, offline wikipedia, open-source, knowledge, software

**Comment by svikrantaxioned** [comment]
Please close this ticket as this ticket is created on https://github.com/kiwix/web
