### ISSUE TITLE
Invalid OPDS XML

### ISSUE THREAD

**Issue by kelson42** [kiwix/libkiwix#925]
OPDS XML is not always valid like:
```
<title>Filtered Entries (lang=eng&amp;category=wikipedia)</title>
```

I guess this is the problem because I had: 
![image](https://user-images.githubusercontent.com/1029718/226188004-06f2d57f-26ff-46c2-87b5-9022b6cc1a5c.png)

First reported at https://github.com/kiwix/libkiwix/pull/920#pullrequestreview-1347498038

**Comment by kelson42** [comment]
@veloman-yunkan Going through the tickets let in the [12.1.0 milestone](https://github.com/kiwix/libkiwix/milestone/7) and it seems this one is the worst and probably as well the easiest to fix. Can you please work on it and secure as much as possible we deliver only valid XML?

**Comment by veloman-yunkan** [comment]
@kelson42 Done
