### ISSUE TITLE
[Feature Request] Use browser and real URLs to view a site.

### ISSUE THREAD

**Issue by Rexadev** [kiwix/libkiwix#926]
I use bookmarks alot. When offline I would like to open a URL of Wikipedia in browser but pulled from zim file. Because I use bookamrks to organize all the things I do and would like to be albe to use my "setup" offline using kiwix.

**Comment by mgautierfr** [comment]
It is interesting but totally out of scope of kiwix.
What you could do is some kind of local dns which return a ip corresponding to your offline setup if you are offline.
But kiwix will not do that.

**Comment by Rexadev** [comment]
> What you could do is some kind of local dns

Any software I can run on OpenWrt or Windows,Linux,MacOS ?

> which return a ip corresponding to your offline setup if you are offline. But kiwix will not do that.

But Kiwix reader has to act as a server. Example DNS software on OS returns 127.0.0.1:8732 will kiwix reader installed understand it and redirect me to the correct "URL"?

**Comment by mgautierfr** [comment]
> Any software I can run on OpenWrt or Windows,Linux,MacOS ?

I don't know. Any dns server running on those platform.

> But Kiwix reader has to act as a server

kiwix-serve is your friend.

**Comment by Rexadev** [comment]
> kiwix-serve is your friend.

Example DNS software on OS returns 127.0.0.1:8732 will kiwix-serve installed understand it and redirect me to the correct "URL"?
