### ISSUE TITLE
meson build requires libzim version ['>=8.1.0'] but libzim (7.2.0) shows to be latest version.

### ISSUE THREAD

**Issue by Bigguysahaj** [kiwix/libkiwix#927]
### issue

![image](https://user-images.githubusercontent.com/70798888/230122836-69fd042b-6804-474b-abcd-25fb4fddc0a6.png)

### after updating
![image](https://user-images.githubusercontent.com/70798888/230122913-054c3c75-5aaa-4eb6-b87f-0fb0df2639b6.png)
What could be the issue, do I need to manually build libzim for the latest version?

**Comment by mgautierfr** [comment]
We have a ppa for libzim (and other) here : https://launchpad.net/~kiwixteam/+archive/ubuntu/release

Or you can indeed build libzim yourself.
