### ISSUE TITLE
Kiwix serve welcome page redesign

### ISSUE THREAD

**Issue by ghost** [kiwix/libkiwix#928]
Here is the Figma URL: https://www.figma.com/file/atKBgNfsDz5MvmsOGHY2ls/kiwix?node-id=126-244&t=E2Opi57AQX4IqwRa-0. You should be referring to "For Developers" tab from the left hand navigation.

Meta Data Description to be considered during the development of page as below (this is only a recommendation, but if you have any alternative data then feel free to use them.)

Title: Kiwix - Kiwix Library: Accessing a Wealth of Knowledge Offline
Description: Access a vast collection of educational content offline with Kiwix library, a free, open-source software application. Enjoy Wikipedia articles, books, and educational videos in multiple languages on your computer or mobile devices, even in areas with limited internet connectivity.
Keywords: .kiwix, kiwix library, offline access, educational content, Wikipedia, books, videos, open-source software, internet connectivity, multiple languages, knowledge, information.

Here are some guidelines for Dev -
- The page title ( banner title ) should be formatted as an H1 tag.
- for listing card it's container should be a div and the listing card should be article tag
- The Listing Card image should me clickable it it should be wrapped under anchor a<img. In anchor tag title should be present
- Card heading should be h2 tag it should also be clickable h2>a
- Download link eg: 50.5 MB should be clickable.

**Comment by Popolechien** [comment]
The figma link has changed and now points to the website redesign (we have no access to history) and OP has closed their account. @kelson42 should we close the issue and reopen a new one?

**Comment by rgaudin** [comment]
Unusable

**Comment by kelson42** [comment]
@rgaudin @Popolechien Actually I still had in view to look at Axioned proposal. Coukd we have a new ticket with the same proposal and a valid link?
