### ISSUE TITLE
Revert "Fix macOS CI python dependency install"

### ISSUE THREAD

**Issue by kelson42** [kiwix/libkiwix#932]
https://github.com/kiwix/libkiwix/pull/931

**Comment by kelson42** [comment]
@rgaudin What thing/ticket should we monitor to know if we can implement this ticket?

**Comment by rgaudin** [comment]
It's already fixed (see [this run](https://github.com/kiwix/libkiwix/actions/runs/4721918514/jobs/8375793441)). We can revert already
