### ISSUE TITLE
gungbe not recognized among languages

### ISSUE THREAD

**Issue by Popolechien** [kiwix/libkiwix#933]
We recently created a couple of zim files of Gungbe (guw.wiktionary/wikipedia/wikiquote.org) but the language does not appear in the selector. Could it be related to the fact that the language code has no official ISO-639-1 code?

**Comment by kelson42** [comment]
@veloman-yunkan Can you please finally fix that one? Seems straight.

**Comment by kelson42** [comment]
@veloman-yunkan Can we please have a fix for this last one?

**Comment by veloman-yunkan** [comment]
@kelson42 Will be ready by the next Kiwix weekly meeting.
