### ISSUE TITLE
External content is inaccessible in the viewer iframe

### ISSUE THREAD

**Issue by veloman-yunkan** [kiwix/libkiwix#943]
Sandboxing of the content in the viewer iframe (introduced by #906 and then reimplemented through #924 & #930) has resulted in links to external resources becoming inoperable in the viewer (no matter if `kiwix-serve` is started with the `--blockexternal` option or not).

This issue was [noticed earlier](https://github.com/kiwix/kiwix-tools/issues/604#issuecomment-1469959262) and since it persisted after #906 was overridden by #924/#930 it definitely needs a dedicated ticket.

@Jaifroid's has [proposed](https://github.com/kiwix/libkiwix/pull/924#issuecomment-1488877171) to fix the issue via making external links to be opened in a new tab/window. At this point I don't see any other solution.

**Comment by Jaifroid** [comment]
Thanks for opening this issue. The (untested in Kiwix Serve) code I suggested is here:

https://github.com/kiwix/kiwix-tools/issues/604#issuecomment-1470013026

(obviously will need to be adapted to the Kiwix Serve environment).

**Comment by Jaifroid** [comment]
Does that ask the user? I haven't seen that directive in action. If it works, it would be better than adding event listeners. So long as the user is protected out of the box (from the browser destroying the iframe, whcih was the very reason we introduced the sandbox in the first place).

**Comment by kelson42** [comment]
> @Jaifroid's has proposed to fix the issue via making external links to be opened in a new tab/window. At this point I don't see any other solution

Kind of acceptable for me, if nobody as a better alternative.

**Comment by Jaifroid** [comment]
Any fix for this issue should also take into account https://github.com/kiwix/kiwix-tools/issues/591. The solution would be broadly the same (if using a click event listener, as opposed to relaxing the sandbox).

**Comment by veloman-yunkan** [comment]
> At this point I don't see any other solution.

It seems that a [workaround](https://github.com/kiwix/libkiwix/pull/946) was found.
