### ISSUE TITLE
Fix documentation config files

### ISSUE THREAD

**Issue by mgautierfr** [kiwix/libkiwix#945]
Readthedocs build are now falling.

See https://github.com/readthedocs/readthedocs.org/issues/10290

**Comment by humitos** [comment]
This should be fixed now. However, we strongly recommend you to create a `.readthedocs.yaml` config file for your project and use `build.os` config key.

**Comment by kelson42** [comment]
Looks like RTD won’t work soon without a dedicated yaml configuration file.

**Comment by mgautierfr** [comment]
Thanks @humitos for the documentation.

Fix also applied on libzim (openzim/libzim#805)
