### ISSUE TITLE
[server] Search endpoint doesn't remove accents from the query.

### ISSUE THREAD

**Issue by mgautierfr** [kiwix/libkiwix#953]
Searching for pattern with a accent return no result, even if the same search without accent give results.

This can be see with the branch `search_remove_accent` (https://github.com/kiwix/libkiwix/compare/main...search_remove_accent).

Adding a `removeAccents(pattern)` fixes the issue about the searching part (we have results) but test still failing wrong encoding
when trying to render the search page (or the test is broken ?)

**Comment by kelson42** [comment]
@mgautierfr @veloman-yunkan Do we knowcwhen this regression has been introduced?

**Comment by mgautierfr** [comment]
> Do we know when this regression has been introduced?

This is not easy to trace that, but it seems this is when removed the libkiwix wrapper around libzim structure.

> On library.kiwix.org, it seems the behaviour is OK.

suggestion is not impacted.
