### ISSUE TITLE
libkiwix should be able to parse catalog/v2/languages and catalog/v2/categories

### ISSUE THREAD

**Issue by juuz0** [kiwix/libkiwix#968]
This will give a common interface to get all languages and categories

**Comment by kelson42** [comment]
@veloman-yunkan @mgautierfr @juuz0 Assuming this would be implemented quickly I have introduced this ticket as last one to fix for 12.1.0 release. Not convinced this is a good idea. Please let me know otherwise, so I can postponed and we can finally release libkiwix 12.1.0.

**Comment by juuz0** [comment]
Probably better to take this out of 12.1.0, mgautierfr may have different ideas on how these needs to be implemented - going by his comment in the PR
