### ISSUE TITLE
Better document API changes

### ISSUE THREAD

**Issue by kelson42** [kiwix/libkiwix#985]
We regularly face situations where the lack of clarity around API changes (and this is true as well for libzim) leads us to uncontrolled movements:
* we don’t follow anymore sementic versionning and this leads to further problem with linux distros
* Responsible of binding don’t do the necessary changes
* Users of the library are not informed properly about new features
* …

what can we do to fix these problems.

**Comment by mgautierfr** [comment]
We should introduce a tool like https://lvc.github.io/abi-compliance-checker/ in our CI to detect a ABI change as soon as possible.

**Comment by kelson42** [comment]
@mgautierfr Seems indeed a good security. I have found as well https://github.com/lvc/abi-compliance-checker but seems not maintained.

... But the other point might be the communication, in particular at release time. Could we have an easy and standard way to communicate these changes?

**Comment by mgautierfr** [comment]
> ... But the other point might be the communication, in particular at release time. Could we have an easy and standard way to communicate these changes?

We have, this is semantic versioning we already follow (except when we don't realize ourselves we break the API)

**Comment by kelson42** [comment]
Update:
* there is no easy way to deploy a tool to check this (no action, old tool to configure, …)
* We have updated the dependencies (kiwix-tools, kiwix-desktop) to not accept new major dependencies per default
* I have updated the release check list to verify if we don‘t have missed a breaking ABI change

At this stage, I believe there is nothing much more we can reasonably do.
